function varargout=sym_sd_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=6;
   return
  case 'npar'
   varargout{1}=11;
   return
  case 'nf'
   varargout{1}=5;
   return
  case 'nx'
   varargout{1}=5;
   return
  case 'tp_del'
   varargout{1}=1;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={[1  2], [3  4  5  6]};
   return
  case 'sys_tau_in'
   varargout{1}=[1  1  2  2  2  2];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1  3  1  4  1  5  1  1  2  2  2  1  3  2  3  1  4  3  4  1  5  2  5  2  6  1  7];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_sd_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2,out_3,out_4,out_5] = sym_sd_demo_rhs_1_0(in1,in2,in3,in4)
%SYM_SD_DEMO_RHS_1_0
%    [OUT_1,OUT_2,OUT_3,OUT_4,OUT_5] = SYM_SD_DEMO_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:30

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_2_n9 = in2(:,9);
in_1_n11 = in1(:,11);
in_1_n12 = in1(:,12);
in_1_n16 = in1(:,16);
in_1_n18 = in1(:,18);
in_1_n21 = in1(:,21);
in_1_n22 = in1(:,22);
in_1_n27 = in1(:,27);
in_1_n31 = in1(:,31);
t2 = in_1_n2+in_2_n1;
t3 = 1.0./t2;
out_1 = t3.*(in_1_n6.*in_2_n3.*in_1_n12-in_1_n1.*in_2_n2.*in_1_n16.*in_1_n18+1.0);
if nargout > 1
    out_2 = in_2_n5.*tanh(in_1_n27)+in_1_n1.*in_2_n4.*t3-1.0;
end
if nargout > 2
    out_3 = in_2_n6.*(in_1_n2-in_1_n3)+in_2_n7.*exp(-in_1_n4.*in_2_n8).*(in_1_n22-in_1_n31);
end
if nargout > 3
    out_4 = in_1_n21.*exp(-in_1_n4.*in_2_n1)-1.0./1.0e+1;
end
if nargout > 4
    out_5 = in_1_n5.*-3.0-in_2_n9+in_1_n11.*3.0;
end
end


function [out_1,out_2,out_3,out_4,out_5] = sym_sd_demo_rhs_1_1(in1,in2,in3,in4)
%SYM_SD_DEMO_RHS_1_1
%    [OUT_1,OUT_2,OUT_3,OUT_4,OUT_5] = SYM_SD_DEMO_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:30

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
in_4_n9 = in4(:,9);
in_1_n12 = in1(:,12);
in_1_n16 = in1(:,16);
in_1_n18 = in1(:,18);
in_1_n21 = in1(:,21);
in_1_n22 = in1(:,22);
in_1_n27 = in1(:,27);
in_1_n31 = in1(:,31);
in_3_n11 = in3(:,11);
in_3_n12 = in3(:,12);
in_3_n16 = in3(:,16);
in_3_n18 = in3(:,18);
in_3_n21 = in3(:,21);
in_3_n22 = in3(:,22);
in_3_n27 = in3(:,27);
in_3_n31 = in3(:,31);
t2 = tanh(in_1_n27);
t3 = in_1_n4.*in_2_n1;
t4 = in_1_n4.*in_2_n8;
t5 = in_1_n2+in_2_n1;
t6 = in_3_n2+in_4_n1;
t7 = -in_1_n31;
t8 = -t3;
t9 = -t4;
t10 = in_1_n22+t7;
t11 = 1.0./t5;
t12 = t11.^2;
out_1 = -t11.*(-in_1_n6.*in_4_n3.*in_1_n12-in_2_n3.*in_3_n6.*in_1_n12-in_1_n6.*in_2_n3.*in_3_n12+in_1_n1.*in_4_n2.*in_1_n16.*in_1_n18+in_2_n2.*in_3_n1.*in_1_n16.*in_1_n18+in_1_n1.*in_2_n2.*in_1_n16.*in_3_n18+in_1_n1.*in_2_n2.*in_1_n18.*in_3_n16)-t6.*t12.*(in_1_n6.*in_2_n3.*in_1_n12-in_1_n1.*in_2_n2.*in_1_n16.*in_1_n18+1.0);
if nargout > 1
    out_2 = in_4_n5.*t2-in_2_n5.*in_3_n27.*(t2.^2-1.0)+in_1_n1.*in_4_n4.*t11+in_2_n4.*in_3_n1.*t11-in_1_n1.*in_2_n4.*t6.*t12;
end
if nargout > 2
    t13 = exp(t8);
    t14 = exp(t9);
    out_3 = in_4_n6.*(in_1_n2-in_1_n3)+in_2_n6.*(in_3_n2-in_3_n3)+in_4_n7.*t10.*t14+in_2_n7.*t14.*(in_3_n22-in_3_n31)-in_2_n7.*t10.*t14.*(in_1_n4.*in_4_n8+in_2_n8.*in_3_n4);
end
if nargout > 3
    out_4 = in_3_n21.*t13-in_1_n21.*t13.*(in_1_n4.*in_4_n1+in_2_n1.*in_3_n4);
end
if nargout > 4
    out_5 = in_3_n5.*-3.0-in_4_n9+in_3_n11.*3.0;
end
end


function [out_1,out_2,out_3,out_4,out_5] = sym_sd_demo_rhs_1_2(in1,in2,in3,in4)
%SYM_SD_DEMO_RHS_1_2
%    [OUT_1,OUT_2,OUT_3,OUT_4,OUT_5] = SYM_SD_DEMO_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:30

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
in_1_n12 = in1(:,12);
in_1_n16 = in1(:,16);
in_1_n18 = in1(:,18);
in_1_n21 = in1(:,21);
in_1_n22 = in1(:,22);
in_1_n27 = in1(:,27);
in_1_n31 = in1(:,31);
in_3_n12 = in3(:,12);
in_3_n16 = in3(:,16);
in_3_n18 = in3(:,18);
in_3_n21 = in3(:,21);
in_3_n22 = in3(:,22);
in_3_n27 = in3(:,27);
in_3_n31 = in3(:,31);
t2 = tanh(in_1_n27);
t3 = in_1_n4.*in_2_n1;
t4 = in_1_n4.*in_2_n8;
t5 = in_1_n4.*in_4_n1;
t6 = in_2_n1.*in_3_n4;
t7 = in_1_n4.*in_4_n8;
t8 = in_2_n8.*in_3_n4;
t9 = in_1_n2+in_2_n1;
t10 = in_3_n2+in_4_n1;
t12 = -in_1_n31;
t13 = -in_3_n31;
t11 = t2.^2;
t14 = -t3;
t15 = -t4;
t16 = t10.^2;
t17 = in_1_n22+t12;
t18 = in_3_n22+t13;
t19 = 1.0./t9;
t25 = t5+t6;
t26 = t7+t8;
t20 = t19.^2;
t21 = t19.^3;
out_1 = -t19.*(in_3_n6.*in_4_n3.*in_1_n12.*-2.0-in_1_n6.*in_4_n3.*in_3_n12.*2.0-in_2_n3.*in_3_n6.*in_3_n12.*2.0+in_3_n1.*in_4_n2.*in_1_n16.*in_1_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n16.*in_3_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n18.*in_3_n16.*2.0+in_2_n2.*in_3_n1.*in_1_n16.*in_3_n18.*2.0+in_2_n2.*in_3_n1.*in_1_n18.*in_3_n16.*2.0+in_1_n1.*in_2_n2.*in_3_n16.*in_3_n18.*2.0)+t16.*t21.*(in_1_n6.*in_2_n3.*in_1_n12-in_1_n1.*in_2_n2.*in_1_n16.*in_1_n18+1.0).*2.0+t10.*t20.*(-in_1_n6.*in_4_n3.*in_1_n12-in_2_n3.*in_3_n6.*in_1_n12-in_1_n6.*in_2_n3.*in_3_n12+in_1_n1.*in_4_n2.*in_1_n16.*in_1_n18+in_2_n2.*in_3_n1.*in_1_n16.*in_1_n18+in_1_n1.*in_2_n2.*in_1_n16.*in_3_n18+in_1_n1.*in_2_n2.*in_1_n18.*in_3_n16).*2.0;
if nargout > 1
    t22 = exp(t14);
    t23 = exp(t15);
    t24 = t11-1.0;
    out_2 = in_3_n1.*in_4_n4.*t19.*2.0-in_4_n5.*in_3_n27.*t24.*2.0+in_1_n1.*in_2_n4.*t16.*t21.*2.0-in_1_n1.*in_4_n4.*t10.*t20.*2.0-in_2_n4.*in_3_n1.*t10.*t20.*2.0+in_2_n5.*in_3_n27.^2.*t2.*t24.*2.0;
end
if nargout > 2
    out_3 = in_4_n6.*(in_3_n2-in_3_n3).*2.0+in_4_n7.*t18.*t23.*2.0-in_2_n7.*t18.*t23.*t26.*2.0-in_4_n7.*t17.*t23.*t26.*2.0+in_2_n7.*t17.*t23.*t26.^2-in_2_n7.*in_3_n4.*in_4_n8.*t17.*t23.*2.0;
end
if nargout > 3
    out_4 = in_1_n21.*t22.*t25.^2-in_3_n21.*t22.*t25.*2.0-in_3_n4.*in_4_n1.*in_1_n21.*t22.*2.0;
end
if nargout > 4
    out_5 = 0.0;
end
end


function [out_1,out_2,out_3,out_4,out_5] = sym_sd_demo_rhs_1_3(in1,in2,in3,in4)
%SYM_SD_DEMO_RHS_1_3
%    [OUT_1,OUT_2,OUT_3,OUT_4,OUT_5] = SYM_SD_DEMO_RHS_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:30

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n4 = in3(:,4);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
in_1_n12 = in1(:,12);
in_1_n16 = in1(:,16);
in_1_n18 = in1(:,18);
in_1_n21 = in1(:,21);
in_1_n22 = in1(:,22);
in_1_n27 = in1(:,27);
in_1_n31 = in1(:,31);
in_3_n12 = in3(:,12);
in_3_n16 = in3(:,16);
in_3_n18 = in3(:,18);
in_3_n21 = in3(:,21);
in_3_n22 = in3(:,22);
in_3_n27 = in3(:,27);
in_3_n31 = in3(:,31);
t2 = tanh(in_1_n27);
t3 = in_1_n4.*in_2_n1;
t4 = in_1_n4.*in_2_n8;
t5 = in_1_n4.*in_4_n1;
t6 = in_2_n1.*in_3_n4;
t7 = in_1_n4.*in_4_n8;
t8 = in_2_n8.*in_3_n4;
t9 = in_1_n2+in_2_n1;
t10 = in_3_n2+in_4_n1;
t11 = in_3_n27.^3;
t13 = -in_1_n31;
t14 = -in_3_n31;
t12 = t2.^2;
t15 = -t3;
t16 = -t4;
t17 = t10.^2;
t18 = t10.^3;
t19 = in_1_n22+t13;
t20 = in_3_n22+t14;
t21 = 1.0./t9.^2;
t22 = 1.0./t9.^3;
t27 = t5+t6;
t28 = t7+t8;
t23 = t21.^2;
out_1 = -(in_3_n6.*in_4_n3.*in_3_n12.*-6.0+in_3_n1.*in_4_n2.*in_1_n16.*in_3_n18.*6.0+in_3_n1.*in_4_n2.*in_1_n18.*in_3_n16.*6.0+in_1_n1.*in_4_n2.*in_3_n16.*in_3_n18.*6.0+in_2_n2.*in_3_n1.*in_3_n16.*in_3_n18.*6.0)./t9-t18.*t23.*(in_1_n6.*in_2_n3.*in_1_n12-in_1_n1.*in_2_n2.*in_1_n16.*in_1_n18+1.0).*6.0-t17.*t22.*(-in_1_n6.*in_4_n3.*in_1_n12-in_2_n3.*in_3_n6.*in_1_n12-in_1_n6.*in_2_n3.*in_3_n12+in_1_n1.*in_4_n2.*in_1_n16.*in_1_n18+in_2_n2.*in_3_n1.*in_1_n16.*in_1_n18+in_1_n1.*in_2_n2.*in_1_n16.*in_3_n18+in_1_n1.*in_2_n2.*in_1_n18.*in_3_n16).*6.0+t10.*t21.*(in_3_n6.*in_4_n3.*in_1_n12.*-2.0-in_1_n6.*in_4_n3.*in_3_n12.*2.0-in_2_n3.*in_3_n6.*in_3_n12.*2.0+in_3_n1.*in_4_n2.*in_1_n16.*in_1_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n16.*in_3_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n18.*in_3_n16.*2.0+in_2_n2.*in_3_n1.*in_1_n16.*in_3_n18.*2.0+in_2_n2.*in_3_n1.*in_1_n18.*in_3_n16.*2.0+in_1_n1.*in_2_n2.*in_3_n16.*in_3_n18.*2.0).*3.0;
if nargout > 1
    t24 = exp(t15);
    t25 = exp(t16);
    t26 = t12-1.0;
    out_2 = in_2_n5.*t11.*t26.^2.*-2.0-in_1_n1.*in_2_n4.*t18.*t23.*6.0+in_1_n1.*in_4_n4.*t17.*t22.*6.0+in_2_n4.*in_3_n1.*t17.*t22.*6.0-in_3_n1.*in_4_n4.*t10.*t21.*6.0-in_2_n5.*t11.*t12.*t26.*4.0+in_4_n5.*in_3_n27.^2.*t2.*t26.*6.0;
end
if nargout > 2
    t29 = t28.^2;
    out_3 = in_2_n7.*t20.*t25.*t29.*3.0+in_4_n7.*t19.*t25.*t29.*3.0-in_4_n7.*t20.*t25.*t28.*6.0-in_2_n7.*t19.*t25.*t28.^3-in_2_n7.*in_3_n4.*in_4_n8.*t20.*t25.*6.0-in_3_n4.*in_4_n7.*in_4_n8.*t19.*t25.*6.0+in_2_n7.*in_3_n4.*in_4_n8.*t19.*t25.*t28.*6.0;
end
if nargout > 3
    out_4 = -in_1_n21.*t24.*t27.^3+in_3_n21.*t24.*t27.^2.*3.0-in_3_n4.*in_4_n1.*in_3_n21.*t24.*6.0+in_3_n4.*in_4_n1.*in_1_n21.*t24.*t27.*6.0;
end
if nargout > 4
    out_5 = 0.0;
end
end


function [out_1,out_2,out_3,out_4,out_5] = sym_sd_demo_rhs_1_4(in1,in2,in3,in4)
%SYM_SD_DEMO_RHS_1_4
%    [OUT_1,OUT_2,OUT_3,OUT_4,OUT_5] = SYM_SD_DEMO_RHS_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:30

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n4 = in3(:,4);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
in_1_n12 = in1(:,12);
in_1_n16 = in1(:,16);
in_1_n18 = in1(:,18);
in_1_n21 = in1(:,21);
in_1_n22 = in1(:,22);
in_1_n27 = in1(:,27);
in_1_n31 = in1(:,31);
in_3_n12 = in3(:,12);
in_3_n16 = in3(:,16);
in_3_n18 = in3(:,18);
in_3_n21 = in3(:,21);
in_3_n22 = in3(:,22);
in_3_n27 = in3(:,27);
in_3_n31 = in3(:,31);
t2 = tanh(in_1_n27);
t3 = in_1_n4.*in_2_n1;
t4 = in_1_n4.*in_2_n8;
t5 = in_1_n4.*in_4_n1;
t6 = in_2_n1.*in_3_n4;
t7 = in_1_n4.*in_4_n8;
t8 = in_2_n8.*in_3_n4;
t9 = in_1_n2+in_2_n1;
t10 = in_3_n2+in_4_n1;
t11 = in_3_n4.^2;
t12 = in_3_n27.^3;
t13 = in_3_n27.^4;
t15 = -in_1_n31;
t16 = -in_3_n31;
t14 = t2.^2;
t17 = -t3;
t18 = -t4;
t19 = t10.^2;
t20 = t10.^3;
t22 = in_1_n22+t15;
t23 = in_3_n22+t16;
t24 = 1.0./t9.^3;
t25 = 1.0./t9.^4;
t26 = 1.0./t9.^5;
t30 = t5+t6;
t31 = t7+t8;
t21 = t19.^2;
out_1 = t21.*t26.*(in_1_n6.*in_2_n3.*in_1_n12-in_1_n1.*in_2_n2.*in_1_n16.*in_1_n18+1.0).*2.4e+1+t20.*t25.*(-in_1_n6.*in_4_n3.*in_1_n12-in_2_n3.*in_3_n6.*in_1_n12-in_1_n6.*in_2_n3.*in_3_n12+in_1_n1.*in_4_n2.*in_1_n16.*in_1_n18+in_2_n2.*in_3_n1.*in_1_n16.*in_1_n18+in_1_n1.*in_2_n2.*in_1_n16.*in_3_n18+in_1_n1.*in_2_n2.*in_1_n18.*in_3_n16).*2.4e+1-t19.*t24.*(in_3_n6.*in_4_n3.*in_1_n12.*-2.0-in_1_n6.*in_4_n3.*in_3_n12.*2.0-in_2_n3.*in_3_n6.*in_3_n12.*2.0+in_3_n1.*in_4_n2.*in_1_n16.*in_1_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n16.*in_3_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n18.*in_3_n16.*2.0+in_2_n2.*in_3_n1.*in_1_n16.*in_3_n18.*2.0+in_2_n2.*in_3_n1.*in_1_n18.*in_3_n16.*2.0+in_1_n1.*in_2_n2.*in_3_n16.*in_3_n18.*2.0).*1.2e+1+1.0./t9.^2.*t10.*(in_3_n6.*in_4_n3.*in_3_n12.*-6.0+in_3_n1.*in_4_n2.*in_1_n16.*in_3_n18.*6.0+in_3_n1.*in_4_n2.*in_1_n18.*in_3_n16.*6.0+in_1_n1.*in_4_n2.*in_3_n16.*in_3_n18.*6.0+in_2_n2.*in_3_n1.*in_3_n16.*in_3_n18.*6.0).*4.0-(in_3_n1.*in_4_n2.*in_3_n16.*in_3_n18.*2.4e+1)./t9;
if nargout > 1
    t27 = exp(t17);
    t28 = exp(t18);
    t29 = t14-1.0;
    t32 = t31.^2;
    t33 = t31.^3;
    t34 = t29.^2;
    out_2 = in_4_n5.*t12.*t34.*-8.0+in_1_n1.*in_2_n4.*t21.*t26.*2.4e+1-in_1_n1.*in_4_n4.*t20.*t25.*2.4e+1-in_2_n4.*in_3_n1.*t20.*t25.*2.4e+1+in_3_n1.*in_4_n4.*t19.*t24.*2.4e+1+in_2_n5.*t2.*t13.*t34.*1.6e+1-in_4_n5.*t12.*t14.*t29.*1.6e+1+in_2_n5.*t2.^3.*t13.*t29.*8.0;
end
if nargout > 2
    out_3 = in_2_n7.*t23.*t28.*t33.*-4.0-in_4_n7.*t22.*t28.*t33.*4.0+in_4_n7.*t23.*t28.*t32.*1.2e+1+in_2_n7.*t22.*t28.*t32.^2-in_3_n4.*in_4_n7.*in_4_n8.*t23.*t28.*2.4e+1+in_2_n7.*in_4_n8.^2.*t11.*t22.*t28.*1.2e+1-in_2_n7.*in_3_n4.*in_4_n8.*t22.*t28.*t32.*1.2e+1+in_2_n7.*in_3_n4.*in_4_n8.*t23.*t28.*t31.*2.4e+1+in_3_n4.*in_4_n7.*in_4_n8.*t22.*t28.*t31.*2.4e+1;
end
if nargout > 3
    out_4 = in_1_n21.*t27.*t30.^4-in_3_n21.*t27.*t30.^3.*4.0+in_4_n1.^2.*in_1_n21.*t11.*t27.*1.2e+1+in_3_n4.*in_4_n1.*in_3_n21.*t27.*t30.*2.4e+1-in_3_n4.*in_4_n1.*in_1_n21.*t27.*t30.^2.*1.2e+1;
end
if nargout > 4
    out_5 = 0.0;
end
end


function [out_1,out_2,out_3,out_4,out_5] = sym_sd_demo_rhs_1_5(in1,in2,in3,in4)
%SYM_SD_DEMO_RHS_1_5
%    [OUT_1,OUT_2,OUT_3,OUT_4,OUT_5] = SYM_SD_DEMO_RHS_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:31

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n4 = in3(:,4);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
in_1_n12 = in1(:,12);
in_1_n16 = in1(:,16);
in_1_n18 = in1(:,18);
in_1_n21 = in1(:,21);
in_1_n22 = in1(:,22);
in_1_n27 = in1(:,27);
in_1_n31 = in1(:,31);
in_3_n12 = in3(:,12);
in_3_n16 = in3(:,16);
in_3_n18 = in3(:,18);
in_3_n21 = in3(:,21);
in_3_n22 = in3(:,22);
in_3_n27 = in3(:,27);
in_3_n31 = in3(:,31);
t2 = tanh(in_1_n27);
t3 = in_1_n4.*in_2_n1;
t4 = in_1_n4.*in_2_n8;
t5 = in_1_n4.*in_4_n1;
t6 = in_2_n1.*in_3_n4;
t7 = in_1_n4.*in_4_n8;
t8 = in_2_n8.*in_3_n4;
t9 = in_1_n2+in_2_n1;
t10 = in_3_n2+in_4_n1;
t11 = in_3_n4.^2;
t12 = in_4_n1.^2;
t13 = in_4_n8.^2;
t14 = in_3_n27.^4;
t15 = in_3_n27.^5;
t17 = -in_1_n31;
t18 = -in_3_n31;
t16 = t2.^2;
t19 = -t3;
t20 = -t4;
t21 = t10.^3;
t22 = t10.^4;
t23 = t10.^5;
t24 = in_1_n22+t17;
t25 = in_3_n22+t18;
t26 = 1.0./t9.^4;
t27 = 1.0./t9.^5;
t28 = 1.0./t9.^6;
out_1 = 1.0./t9.^3.*t10.^2.*(in_3_n6.*in_4_n3.*in_3_n12.*-6.0+in_3_n1.*in_4_n2.*in_1_n16.*in_3_n18.*6.0+in_3_n1.*in_4_n2.*in_1_n18.*in_3_n16.*6.0+in_1_n1.*in_4_n2.*in_3_n16.*in_3_n18.*6.0+in_2_n2.*in_3_n1.*in_3_n16.*in_3_n18.*6.0).*-2.0e+1-t23.*t28.*(in_1_n6.*in_2_n3.*in_1_n12-in_1_n1.*in_2_n2.*in_1_n16.*in_1_n18+1.0).*1.2e+2-t22.*t27.*(-in_1_n6.*in_4_n3.*in_1_n12-in_2_n3.*in_3_n6.*in_1_n12-in_1_n6.*in_2_n3.*in_3_n12+in_1_n1.*in_4_n2.*in_1_n16.*in_1_n18+in_2_n2.*in_3_n1.*in_1_n16.*in_1_n18+in_1_n1.*in_2_n2.*in_1_n16.*in_3_n18+in_1_n1.*in_2_n2.*in_1_n18.*in_3_n16).*1.2e+2+t21.*t26.*(in_3_n6.*in_4_n3.*in_1_n12.*-2.0-in_1_n6.*in_4_n3.*in_3_n12.*2.0-in_2_n3.*in_3_n6.*in_3_n12.*2.0+in_3_n1.*in_4_n2.*in_1_n16.*in_1_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n16.*in_3_n18.*2.0+in_1_n1.*in_4_n2.*in_1_n18.*in_3_n16.*2.0+in_2_n2.*in_3_n1.*in_1_n16.*in_3_n18.*2.0+in_2_n2.*in_3_n1.*in_1_n18.*in_3_n16.*2.0+in_1_n1.*in_2_n2.*in_3_n16.*in_3_n18.*2.0).*6.0e+1+in_3_n1.*in_4_n2.*in_3_n16.*in_3_n18.*1.0./t9.^2.*t10.*1.2e+2;
if nargout > 1
    t32 = t5+t6;
    t33 = t7+t8;
    t29 = exp(t19);
    t30 = exp(t20);
    t31 = t16-1.0;
    t34 = t33.^2;
    t35 = t33.^3;
    t36 = t34.^2;
    t37 = t31.^2;
    out_2 = in_2_n5.*t15.*t31.^3.*-1.6e+1-in_1_n1.*in_2_n4.*t23.*t28.*1.2e+2+in_1_n1.*in_4_n4.*t22.*t27.*1.2e+2+in_2_n4.*in_3_n1.*t22.*t27.*1.2e+2-in_3_n1.*in_4_n4.*t21.*t26.*1.2e+2-in_2_n5.*t15.*t16.*t37.*8.8e+1+in_4_n5.*t2.*t14.*t37.*8.0e+1-in_2_n5.*t15.*t16.^2.*t31.*1.6e+1+in_4_n5.*t2.^3.*t14.*t31.*4.0e+1;
end
if nargout > 2
    out_3 = in_2_n7.*t25.*t30.*t36.*5.0+in_4_n7.*t24.*t30.*t36.*5.0-in_4_n7.*t25.*t30.*t35.*2.0e+1-in_2_n7.*t24.*t30.*t33.^5+in_2_n7.*t11.*t13.*t25.*t30.*6.0e+1+in_4_n7.*t11.*t13.*t24.*t30.*6.0e+1-in_2_n7.*t11.*t13.*t24.*t30.*t33.*6.0e+1+in_2_n7.*in_3_n4.*in_4_n8.*t24.*t30.*t35.*2.0e+1-in_2_n7.*in_3_n4.*in_4_n8.*t25.*t30.*t34.*6.0e+1-in_3_n4.*in_4_n7.*in_4_n8.*t24.*t30.*t34.*6.0e+1+in_3_n4.*in_4_n7.*in_4_n8.*t25.*t30.*t33.*1.2e+2;
end
if nargout > 3
    out_4 = -in_1_n21.*t29.*t32.^5+in_3_n21.*t29.*t32.^4.*5.0+in_3_n21.*t11.*t12.*t29.*6.0e+1-in_1_n21.*t11.*t12.*t29.*t32.*6.0e+1+in_3_n4.*in_4_n1.*in_1_n21.*t29.*t32.^3.*2.0e+1-in_3_n4.*in_4_n1.*in_3_n21.*t29.*t32.^2.*6.0e+1;
end
if nargout > 4
    out_5 = 0.0;
end
end


function [out_1,out_2] = sym_sd_demo_tau_1_0(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_1_0
%    [OUT_1,OUT_2] = SYM_SD_DEMO_TAU_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:31

in_2_n10 = in2(:,10);
in_2_n11 = in2(:,11);
out_1 = in_2_n10;
if nargout > 1
    out_2 = in_2_n11;
end
end


function [out_1,out_2] = sym_sd_demo_tau_1_1(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_1_1
%    [OUT_1,OUT_2] = SYM_SD_DEMO_TAU_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:31

in_4_n10 = in4(:,10);
in_4_n11 = in4(:,11);
out_1 = in_4_n10;
if nargout > 1
    out_2 = in_4_n11;
end
end


function [out_1,out_2] = sym_sd_demo_tau_1_2(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_1_2
%    [OUT_1,OUT_2] = SYM_SD_DEMO_TAU_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:31

out_1 = 0.0;
if nargout > 1
    out_2 = 0.0;
end
end


function [out_1,out_2] = sym_sd_demo_tau_1_3(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_1_3
%    [OUT_1,OUT_2] = SYM_SD_DEMO_TAU_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:31

out_1 = 0.0;
if nargout > 1
    out_2 = 0.0;
end
end


function [out_1,out_2] = sym_sd_demo_tau_1_4(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_1_4
%    [OUT_1,OUT_2] = SYM_SD_DEMO_TAU_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:31

out_1 = 0.0;
if nargout > 1
    out_2 = 0.0;
end
end


function [out_1,out_2] = sym_sd_demo_tau_1_5(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_1_5
%    [OUT_1,OUT_2] = SYM_SD_DEMO_TAU_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:31

out_1 = 0.0;
if nargout > 1
    out_2 = 0.0;
end
end


function [out_1,out_2,out_3,out_4] = sym_sd_demo_tau_2_0(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_2_0
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_SD_DEMO_TAU_2_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:32

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n7 = in1(:,7);
in_2_n5 = in2(:,5);
in_1_n12 = in1(:,12);
in_2_n10 = in2(:,10);
out_1 = in_1_n2.*in_1_n7.*in_2_n5.*in_2_n10+2.0;
if nargout > 1
    out_2 = -1.0./(in_1_n1.*in_1_n12+1.0)+1.0;
end
if nargout > 2
    out_3 = in_1_n4;
end
if nargout > 3
    out_4 = in_1_n5;
end
end


function [out_1,out_2,out_3,out_4] = sym_sd_demo_tau_2_1(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_2_1
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_SD_DEMO_TAU_2_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:32

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n7 = in1(:,7);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n7 = in3(:,7);
in_4_n5 = in4(:,5);
in_1_n12 = in1(:,12);
in_2_n10 = in2(:,10);
in_3_n12 = in3(:,12);
in_4_n10 = in4(:,10);
out_1 = in_1_n2.*in_1_n7.*in_4_n5.*in_2_n10+in_1_n2.*in_2_n5.*in_3_n7.*in_2_n10+in_1_n7.*in_2_n5.*in_3_n2.*in_2_n10+in_1_n2.*in_1_n7.*in_2_n5.*in_4_n10;
if nargout > 1
    out_2 = 1.0./(in_1_n1.*in_1_n12+1.0).^2.*(in_3_n1.*in_1_n12+in_1_n1.*in_3_n12);
end
if nargout > 2
    out_3 = in_3_n4;
end
if nargout > 3
    out_4 = in_3_n5;
end
end


function [out_1,out_2,out_3,out_4] = sym_sd_demo_tau_2_2(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_2_2
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_SD_DEMO_TAU_2_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:32

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n7 = in1(:,7);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n7 = in3(:,7);
in_4_n5 = in4(:,5);
in_1_n12 = in1(:,12);
in_2_n10 = in2(:,10);
in_3_n12 = in3(:,12);
in_4_n10 = in4(:,10);
out_1 = in_1_n2.*in_3_n7.*in_4_n5.*in_2_n10.*2.0+in_1_n7.*in_3_n2.*in_4_n5.*in_2_n10.*2.0+in_2_n5.*in_3_n2.*in_3_n7.*in_2_n10.*2.0+in_1_n2.*in_1_n7.*in_4_n5.*in_4_n10.*2.0+in_1_n2.*in_2_n5.*in_3_n7.*in_4_n10.*2.0+in_1_n7.*in_2_n5.*in_3_n2.*in_4_n10.*2.0;
if nargout > 1
    t2 = in_1_n1.*in_1_n12;
    t3 = t2+1.0;
    out_2 = 1.0./t3.^3.*(in_3_n1.*in_1_n12+in_1_n1.*in_3_n12).^2.*-2.0+in_3_n1.*in_3_n12.*1.0./t3.^2.*2.0;
end
if nargout > 2
    out_3 = 0.0;
end
if nargout > 3
    out_4 = 0.0;
end
end


function [out_1,out_2,out_3,out_4] = sym_sd_demo_tau_2_3(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_2_3
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_SD_DEMO_TAU_2_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:32

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n7 = in1(:,7);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n7 = in3(:,7);
in_4_n5 = in4(:,5);
in_1_n12 = in1(:,12);
in_2_n10 = in2(:,10);
in_3_n12 = in3(:,12);
in_4_n10 = in4(:,10);
out_1 = in_3_n2.*in_3_n7.*in_4_n5.*in_2_n10.*6.0+in_1_n2.*in_3_n7.*in_4_n5.*in_4_n10.*6.0+in_1_n7.*in_3_n2.*in_4_n5.*in_4_n10.*6.0+in_2_n5.*in_3_n2.*in_3_n7.*in_4_n10.*6.0;
if nargout > 1
    t2 = in_1_n1.*in_1_n12;
    t3 = in_3_n1.*in_1_n12;
    t4 = in_1_n1.*in_3_n12;
    t5 = t2+1.0;
    t6 = t3+t4;
    out_2 = 1.0./t5.^4.*t6.^3.*6.0-in_3_n1.*in_3_n12.*1.0./t5.^3.*t6.*1.2e+1;
end
if nargout > 2
    out_3 = 0.0;
end
if nargout > 3
    out_4 = 0.0;
end
end


function [out_1,out_2,out_3,out_4] = sym_sd_demo_tau_2_4(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_2_4
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_SD_DEMO_TAU_2_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:32

in_1_n1 = in1(:,1);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n7 = in3(:,7);
in_4_n5 = in4(:,5);
in_1_n12 = in1(:,12);
in_3_n12 = in3(:,12);
in_4_n10 = in4(:,10);
out_1 = in_3_n2.*in_3_n7.*in_4_n5.*in_4_n10.*2.4e+1;
if nargout > 1
    t2 = in_1_n1.*in_1_n12;
    t3 = in_3_n1.*in_1_n12;
    t4 = in_1_n1.*in_3_n12;
    t5 = t2+1.0;
    t6 = t3+t4;
    out_2 = 1.0./t5.^5.*t6.^4.*-2.4e+1-in_3_n1.^2.*in_3_n12.^2.*1.0./t5.^3.*2.4e+1+in_3_n1.*in_3_n12.*1.0./t5.^4.*t6.^2.*7.2e+1;
end
if nargout > 2
    out_3 = 0.0;
end
if nargout > 3
    out_4 = 0.0;
end
end


function [out_1,out_2,out_3,out_4] = sym_sd_demo_tau_2_5(in1,in2,in3,in4)
%SYM_SD_DEMO_TAU_2_5
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_SD_DEMO_TAU_2_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:05:32

in_1_n1 = in1(:,1);
in_3_n1 = in3(:,1);
in_1_n12 = in1(:,12);
in_3_n12 = in3(:,12);
out_1 = 0.0;
if nargout > 1
    t2 = in_1_n1.*in_1_n12;
    t3 = in_3_n1.*in_1_n12;
    t4 = in_1_n1.*in_3_n12;
    t5 = t2+1.0;
    t6 = t3+t4;
    out_2 = 1.0./t5.^6.*t6.^5.*1.2e+2+in_3_n1.^2.*in_3_n12.^2.*1.0./t5.^4.*t6.*3.6e+2-in_3_n1.*in_3_n12.*1.0./t5.^5.*t6.^3.*4.8e+2;
end
if nargout > 2
    out_3 = 0.0;
end
if nargout > 3
    out_4 = 0.0;
end
end

