%% introduce equation and variable monitoring gap between x_-(1) and x_+(0)
function prob=add_gap_monitor(prob,gapname,uidx,maps,adj)
prob=coco_add_glue(prob,'gap',...
    uidx.u_plus(maps.u_plus.x0_idx(1)),...
    uidx.u_minus(maps.u_minus.x1_idx(1)),...
    0,gapname,'inactive');
prob=coco_add_event(prob,'GAP',gapname,0);
if nargin<5 ||~adj.do
    return
end
prob=loc_add_adjt(prob,'gap',adj,'d.gap','aidx',...
    [adj.idx.u_plus( adj.opt.u_plus.x0_idx(1));...
     adj.idx.u_minus(adj.opt.u_minus.x1_idx(1))]);
end
