function varargout=bc_umfile(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=4;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('T',1:1,'x0',2:4,'x1',5:7,'par',8:14);
   return
  case 'argsize'
   varargout{1}=struct('T',1,'x0',3,'x1',3,'par',7);
   return
  case 'vector'
   varargout{1}=struct('T',1,'x0',1,'x1',1,'par',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('bc_umfile_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});




function [out1,out2,out3] = bc_umfile_rhs_0(T,x0,p0,q0,x1,p1,q1,r,cm,beta,omega,cp,a,phi,T_dev,x0_dev,p0_dev,q0_dev,x1_dev,p1_dev,q1_dev,r_dev,cm_dev,beta_dev,omega_dev,cp_dev,a_dev,phi_dev)
%BC_UMFILE_RHS_0
%    [OUT1,OUT2,OUT3] = BC_UMFILE_RHS_0(T,X0,P0,Q0,X1,P1,Q1,R,CM,BETA,OMEGA,CP,A,PHI,T_DEV,X0_DEV,P0_DEV,Q0_DEV,X1_DEV,P1_DEV,Q1_DEV,R_DEV,CM_DEV,BETA_DEV,OMEGA_DEV,CP_DEV,A_DEV,PHI_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    04-May-2023 17:32:20

out1 = -a+(cm+x0).^2;
if nargout > 1
    t2 = sqrt(2.0);
    out2 = p1-(t2.*cos(phi))./2.0;
end
if nargout > 2
    out3 = q1-(t2.*sin(phi))./2.0;
end


function [out1,out2,out3] = bc_umfile_rhs_1(T,x0,p0,q0,x1,p1,q1,r,cm,beta,omega,cp,a,phi,T_dev,x0_dev,p0_dev,q0_dev,x1_dev,p1_dev,q1_dev,r_dev,cm_dev,beta_dev,omega_dev,cp_dev,a_dev,phi_dev)
%BC_UMFILE_RHS_1
%    [OUT1,OUT2,OUT3] = BC_UMFILE_RHS_1(T,X0,P0,Q0,X1,P1,Q1,R,CM,BETA,OMEGA,CP,A,PHI,T_DEV,X0_DEV,P0_DEV,Q0_DEV,X1_DEV,P1_DEV,Q1_DEV,R_DEV,CM_DEV,BETA_DEV,OMEGA_DEV,CP_DEV,A_DEV,PHI_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    04-May-2023 17:32:20

out1 = -a_dev+(cm+x0).*(cm_dev+x0_dev).*2.0;
if nargout > 1
    t2 = sqrt(2.0);
    out2 = p1_dev+(phi_dev.*t2.*sin(phi))./2.0;
end
if nargout > 2
    out3 = q1_dev-(phi_dev.*t2.*cos(phi))./2.0;
end


function [out1,out2,out3] = bc_umfile_rhs_2(T,x0,p0,q0,x1,p1,q1,r,cm,beta,omega,cp,a,phi,T_dev,x0_dev,p0_dev,q0_dev,x1_dev,p1_dev,q1_dev,r_dev,cm_dev,beta_dev,omega_dev,cp_dev,a_dev,phi_dev)
%BC_UMFILE_RHS_2
%    [OUT1,OUT2,OUT3] = BC_UMFILE_RHS_2(T,X0,P0,Q0,X1,P1,Q1,R,CM,BETA,OMEGA,CP,A,PHI,T_DEV,X0_DEV,P0_DEV,Q0_DEV,X1_DEV,P1_DEV,Q1_DEV,R_DEV,CM_DEV,BETA_DEV,OMEGA_DEV,CP_DEV,A_DEV,PHI_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    04-May-2023 17:32:20

out1 = (cm_dev+x0_dev).^2.*2.0;
if nargout > 1
    t2 = phi_dev.^2;
    t3 = sqrt(2.0);
    out2 = (t2.*t3.*cos(phi))./2.0;
end
if nargout > 2
    out3 = (t2.*t3.*sin(phi))./2.0;
end

