function varargout=r_tipping_bc_plus(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=4;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('T',1:1,'x0',2:4,'x1',5:7,'par',8:14);
   return
  case 'argsize'
   varargout{1}=struct('T',1,'x0',3,'x1',3,'par',7);
   return
  case 'vector'
   varargout{1}=struct('T',0,'x0',1,'x1',1,'par',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('r_tipping_bc_plus_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = r_tipping_bc_plus_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%R_TIPPING_BC_PLUS_RHS_0
%    [OUT1,OUT2] = R_TIPPING_BC_PLUS_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:45

t2 = sqrt(2.0);
out1 = in3-(t2.*cos(in14))./2.0;
if nargout > 1
    out2 = in4-(t2.*sin(in14))./2.0;
end
end


function [out1,out2] = r_tipping_bc_plus_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%R_TIPPING_BC_PLUS_RHS_1
%    [OUT1,OUT2] = R_TIPPING_BC_PLUS_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:45

t2 = sqrt(2.0);
out1 = in17+(in28.*t2.*sin(in14))./2.0;
if nargout > 1
    out2 = in18-(in28.*t2.*cos(in14))./2.0;
end
end


function [out1,out2] = r_tipping_bc_plus_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%R_TIPPING_BC_PLUS_RHS_2
%    [OUT1,OUT2] = R_TIPPING_BC_PLUS_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:45

t2 = in28.^2;
t3 = sqrt(2.0);
out1 = (t2.*t3.*cos(in14))./2.0;
if nargout > 1
    out2 = (t2.*t3.*sin(in14))./2.0;
end
end

