function varargout=r_tipping_rhs(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'par',4:10);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'par',7);
   return
  case 'vector'
   varargout{1}=struct('x',1,'par',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('r_tipping_rhs_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = r_tipping_rhs_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%R_TIPPING_RHS_RHS_0
%    [OUT1,OUT2,OUT3] = R_TIPPING_RHS_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:44

t2 = in2.^2;
t3 = in3.^2;
t4 = t2+t3;
out1 = -in9+(in1+in5-t4.*(in5-in8)+in3.*in6.*sqrt(t4)).^2;
if nargout > 1
    t5 = in4.*t4;
    t6 = -t5;
    t7 = in4+t6;
    out2 = in3.*in7+in2.*t7;
end
if nargout > 2
    out3 = -in2.*in7+in3.*t7;
end
end


function [out1,out2,out3] = r_tipping_rhs_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%R_TIPPING_RHS_RHS_1
%    [OUT1,OUT2,OUT3] = R_TIPPING_RHS_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:44

t2 = in2.^2;
t3 = in3.^2;
t4 = in2.*in12.*2.0;
t5 = in3.*in13.*2.0;
t6 = -in8;
t7 = -in14;
t8 = in5+t6;
t9 = t2+t3;
t12 = t4+t5;
t10 = in4.*t9;
t11 = in14.*t9;
t13 = sqrt(t9);
out1 = -in19+(in1+in5-t8.*t9+in3.*in6.*t13).*(in11+in15-t8.*t12-t9.*(in15-in18)+in3.*in16.*t13+in6.*in13.*t13+(in3.*in6.*t12)./(t13.*2.0)).*2.0;
if nargout > 1
    t14 = in4.*t12;
    t15 = -t10;
    t17 = t7+t11+t14;
    t16 = in4+t15;
    out2 = in3.*in17+in7.*in13-in2.*t17+in12.*t16;
end
if nargout > 2
    out3 = -in2.*in17-in7.*in12-in3.*t17+in13.*t16;
end
end


function [out1,out2,out3] = r_tipping_rhs_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%R_TIPPING_RHS_RHS_2
%    [OUT1,OUT2,OUT3] = R_TIPPING_RHS_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:44

t2 = in2.^2;
t3 = in3.^2;
t4 = in12.^2;
t5 = in13.^2;
t6 = in2.*in12.*2.0;
t7 = in3.*in13.*2.0;
t8 = -in8;
t9 = -in14;
t10 = -in18;
t11 = t4.*2.0;
t12 = t5.*2.0;
t13 = in5+t8;
t14 = in15+t10;
t15 = t2+t3;
t17 = t6+t7;
t16 = in14.*t15;
t18 = sqrt(t15);
t19 = in4.*t17;
t20 = t11+t12;
t22 = in14.*t17.*2.0;
t21 = 1.0./t18;
out1 = (in1+in5-t13.*t15+in3.*in6.*t18).*(t14.*t17.*-2.0-t13.*t20+in13.*in16.*t18.*2.0+(in3.*in6.*t20.*t21)./2.0+in3.*in16.*t17.*t21+in6.*in13.*t17.*t21-(in3.*in6.*t17.^2.*t21.^3)./4.0).*2.0+(in11+in15-t14.*t15-t13.*t17+in3.*in16.*t18+in6.*in13.*t18+(in3.*in6.*t17.*t21)./2.0).^2.*2.0;
if nargout > 1
    t23 = in4.*t20;
    t24 = t9+t16+t19;
    t25 = t22+t23;
    out2 = in13.*in17.*2.0-in2.*t25-in12.*t24.*2.0;
end
if nargout > 2
    out3 = in12.*in17.*-2.0-in3.*t25-in13.*t24.*2.0;
end
end

