function varargout=r_tipping_bc_gamma(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=4;
   return
  case 'nout'
   varargout{1}=4;
   return
  case 'argrange'
   varargout{1}=struct('T',1:1,'x0',2:4,'x1',5:7,'par',8:14);
   return
  case 'argsize'
   varargout{1}=struct('T',1,'x0',3,'x1',3,'par',7);
   return
  case 'vector'
   varargout{1}=struct('T',0,'x0',1,'x1',1,'par',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=4;
order=varargin{1};
f=str2func(sprintf('r_tipping_bc_gamma_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4] = r_tipping_bc_gamma_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%R_TIPPING_BC_GAMMA_RHS_0
%    [OUT1,OUT2,OUT3,OUT4] = R_TIPPING_BC_GAMMA_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:45

out1 = in2-in5;
if nargout > 1
    out2 = in3-in6;
end
if nargout > 2
    t2 = -in7;
    out3 = in4+t2;
end
if nargout > 3
    out4 = t2.*cos(in14)+in6.*sin(in14);
end
end


function [out1,out2,out3,out4] = r_tipping_bc_gamma_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%R_TIPPING_BC_GAMMA_RHS_1
%    [OUT1,OUT2,OUT3,OUT4] = R_TIPPING_BC_GAMMA_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:45

out1 = in16-in19;
if nargout > 1
    out2 = in17-in20;
end
if nargout > 2
    out3 = in18-in21;
end
if nargout > 3
    t2 = cos(in14);
    t3 = sin(in14);
    out4 = in20.*t3-in21.*t2+in6.*in28.*t2+in7.*in28.*t3;
end
end


function [out1,out2,out3,out4] = r_tipping_bc_gamma_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28)
%R_TIPPING_BC_GAMMA_RHS_2
%    [OUT1,OUT2,OUT3,OUT4] = R_TIPPING_BC_GAMMA_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-Dec-2025 16:47:45

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = 0.0;
end
if nargout > 3
    t2 = cos(in14);
    t3 = sin(in14);
    t4 = in28.^2;
    out4 = in20.*in28.*t2.*2.0+in21.*in28.*t3.*2.0-in6.*t3.*t4+in7.*t2.*t4;
end
end

