function res=br_standard_bifurcations(funcs,mth,type,p,varargin)
args={'critical',true};
sargs={'args',{args}};
xargs=[{'exclude_trivial',true},args];
scargs={'args',{xargs}};
bifs=struct(...
    'hopf', struct('res',@(lambda)real(lambda),sargs{:}),...
    'fold', struct('res',@(lambda)real(lambda),sargs{:}),...
    'pfold',struct('res',@(mu)real(mu-1),sargs{:}),...
    'poev1',struct('res',@(mu)real(mu-1),sargs{:}),...
    'tr',   struct('res',@(mu)abs(mu)-1,scargs{:}),...
    'pd',   struct('res',@(mu)real(mu+1),scargs{:}),...
    'hoho', struct('res',@(lambda)real(lambda),scargs{:}),...
    'zeho', struct('res',@(lambda)real(lambda),scargs{:}),...
    'hoze', struct('res',@(lambda)real(lambda),scargs{:}));
[nunst,dom]=GetStability(p,'method',mth,bifs.(type).args{:},...
    'funcs',funcs,varargin{:}); %#ok<ASGLU>
res=bifs.(type).res(dom);
if isnan(res)
    res=-Inf;
end
end
