function varargout=sym_humphriesetal(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=2;
   return
  case 'npar'
   varargout{1}=6;
   return
  case 'nf'
   varargout{1}=1;
   return
  case 'nx'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=1;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={[1], [2]};
   return
  case 'sys_tau_in'
   varargout{1}=[1  2];
   return
  case 'xpattern'
   varargout{1}=[1  1  1  2  1  3];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_humphriesetal_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function out_1 = sym_humphriesetal_rhs_1_0(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_RHS_1_0
%    OUT_1 = SYM_HUMPHRIESETAL_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n5 = in2(:,5);
out_1 = -in_1_n2.*in_2_n1-in_1_n3.*in_2_n2-in_1_n1.*in_2_n5;
end


function out_1 = sym_humphriesetal_rhs_1_1(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_RHS_1_1
%    OUT_1 = SYM_HUMPHRIESETAL_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n5 = in4(:,5);
out_1 = -in_1_n2.*in_4_n1-in_2_n1.*in_3_n2-in_1_n3.*in_4_n2-in_2_n2.*in_3_n3-in_1_n1.*in_4_n5-in_2_n5.*in_3_n1;
end


function out_1 = sym_humphriesetal_rhs_1_2(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_RHS_1_2
%    OUT_1 = SYM_HUMPHRIESETAL_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n5 = in4(:,5);
out_1 = in_3_n2.*in_4_n1.*-2.0-in_3_n3.*in_4_n2.*2.0-in_3_n1.*in_4_n5.*2.0;
end


function out_1 = sym_humphriesetal_rhs_1_3(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_RHS_1_3
%    OUT_1 = SYM_HUMPHRIESETAL_RHS_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_rhs_1_4(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_RHS_1_4
%    OUT_1 = SYM_HUMPHRIESETAL_RHS_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_rhs_1_5(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_RHS_1_5
%    OUT_1 = SYM_HUMPHRIESETAL_RHS_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_tau_1_0(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_1_0
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_1_n1 = in1(:,1);
in_2_n3 = in2(:,3);
in_2_n6 = in2(:,6);
out_1 = in_2_n3+in_1_n1.*in_2_n6;
end


function out_1 = sym_humphriesetal_tau_1_1(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_1_1
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_1_n1 = in1(:,1);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_4_n3 = in4(:,3);
in_4_n6 = in4(:,6);
out_1 = in_4_n3+in_1_n1.*in_4_n6+in_2_n6.*in_3_n1;
end


function out_1 = sym_humphriesetal_tau_1_2(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_1_2
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_3_n1 = in3(:,1);
in_4_n6 = in4(:,6);
out_1 = in_3_n1.*in_4_n6.*2.0;
end


function out_1 = sym_humphriesetal_tau_1_3(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_1_3
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_tau_1_4(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_1_4
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_tau_1_5(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_1_5
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_tau_2_0(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_2_0
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_2_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_1_n1 = in1(:,1);
in_2_n4 = in2(:,4);
in_2_n6 = in2(:,6);
out_1 = in_2_n4+in_1_n1.*in_2_n6;
end


function out_1 = sym_humphriesetal_tau_2_1(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_2_1
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_2_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_1_n1 = in1(:,1);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_4_n4 = in4(:,4);
in_4_n6 = in4(:,6);
out_1 = in_4_n4+in_1_n1.*in_4_n6+in_2_n6.*in_3_n1;
end


function out_1 = sym_humphriesetal_tau_2_2(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_2_2
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_2_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:44

in_3_n1 = in3(:,1);
in_4_n6 = in4(:,6);
out_1 = in_3_n1.*in_4_n6.*2.0;
end


function out_1 = sym_humphriesetal_tau_2_3(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_2_3
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_2_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:45

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_tau_2_4(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_2_4
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_2_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:45

out_1 = 0.0;
end


function out_1 = sym_humphriesetal_tau_2_5(in1,in2,in3,in4)
%SYM_HUMPHRIESETAL_TAU_2_5
%    OUT_1 = SYM_HUMPHRIESETAL_TAU_2_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    24-Feb-2025 17:51:45

out_1 = 0.0;
end

