function varargout=sym_balancing(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'npar'
   varargout{1}=3;
   return
  case 'nf'
   varargout{1}=2;
   return
  case 'nx'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1  1  2  2  2];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_balancing_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2] = sym_balancing_rhs_1_0(in1,in2,in3,in4)
%SYM_BALANCING_RHS_1_0
%    [OUT_1,OUT_2] = SYM_BALANCING_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Feb-2025 18:56:44

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
out_1 = in_1_n2;
if nargout > 1
    out_2 = sin(in_1_n1)-cos(in_1_n1).*(in_1_n3.*in_2_n1+in_1_n4.*in_2_n2);
end
end


function [out_1,out_2] = sym_balancing_rhs_1_1(in1,in2,in3,in4)
%SYM_BALANCING_RHS_1_1
%    [OUT_1,OUT_2] = SYM_BALANCING_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Feb-2025 18:56:44

in_1_n1 = in1(:,1);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
out_1 = in_3_n2;
if nargout > 1
    t2 = cos(in_1_n1);
    out_2 = in_3_n1.*t2-t2.*(in_1_n3.*in_4_n1+in_2_n1.*in_3_n3+in_1_n4.*in_4_n2+in_2_n2.*in_3_n4)+in_3_n1.*sin(in_1_n1).*(in_1_n3.*in_2_n1+in_1_n4.*in_2_n2);
end
end


function [out_1,out_2] = sym_balancing_rhs_1_2(in1,in2,in3,in4)
%SYM_BALANCING_RHS_1_2
%    [OUT_1,OUT_2] = SYM_BALANCING_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Feb-2025 18:56:45

in_1_n1 = in1(:,1);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n1 = in3(:,1);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
out_1 = 0.0;
if nargout > 1
    t2 = cos(in_1_n1);
    t3 = sin(in_1_n1);
    t4 = in_3_n1.^2;
    out_2 = -t3.*t4-t2.*(in_3_n3.*in_4_n1.*2.0+in_3_n4.*in_4_n2.*2.0)+t2.*t4.*(in_1_n3.*in_2_n1+in_1_n4.*in_2_n2)+in_3_n1.*t3.*(in_1_n3.*in_4_n1+in_2_n1.*in_3_n3+in_1_n4.*in_4_n2+in_2_n2.*in_3_n4).*2.0;
end
end


function [out_1,out_2] = sym_balancing_rhs_1_3(in1,in2,in3,in4)
%SYM_BALANCING_RHS_1_3
%    [OUT_1,OUT_2] = SYM_BALANCING_RHS_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Feb-2025 18:56:45

in_1_n1 = in1(:,1);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n1 = in3(:,1);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
out_1 = 0.0;
if nargout > 1
    t2 = cos(in_1_n1);
    t3 = sin(in_1_n1);
    t4 = in_3_n1.^3;
    out_2 = -t2.*t4+in_3_n1.*t3.*(in_3_n3.*in_4_n1.*2.0+in_3_n4.*in_4_n2.*2.0).*3.0-t3.*t4.*(in_1_n3.*in_2_n1+in_1_n4.*in_2_n2)+in_3_n1.^2.*t2.*(in_1_n3.*in_4_n1+in_2_n1.*in_3_n3+in_1_n4.*in_4_n2+in_2_n2.*in_3_n4).*3.0;
end
end


function [out_1,out_2] = sym_balancing_rhs_1_4(in1,in2,in3,in4)
%SYM_BALANCING_RHS_1_4
%    [OUT_1,OUT_2] = SYM_BALANCING_RHS_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Feb-2025 18:56:45

in_1_n1 = in1(:,1);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n1 = in3(:,1);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
out_1 = 0.0;
if nargout > 1
    t2 = cos(in_1_n1);
    t3 = sin(in_1_n1);
    t4 = in_3_n1.^4;
    out_2 = t3.*t4-t2.*t4.*(in_1_n3.*in_2_n1+in_1_n4.*in_2_n2)+in_3_n1.^2.*t2.*(in_3_n3.*in_4_n1.*2.0+in_3_n4.*in_4_n2.*2.0).*6.0-in_3_n1.^3.*t3.*(in_1_n3.*in_4_n1+in_2_n1.*in_3_n3+in_1_n4.*in_4_n2+in_2_n2.*in_3_n4).*4.0;
end
end


function [out_1,out_2] = sym_balancing_rhs_1_5(in1,in2,in3,in4)
%SYM_BALANCING_RHS_1_5
%    [OUT_1,OUT_2] = SYM_BALANCING_RHS_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Feb-2025 18:56:45

in_1_n1 = in1(:,1);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n1 = in3(:,1);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
out_1 = 0.0;
if nargout > 1
    t2 = cos(in_1_n1);
    t3 = sin(in_1_n1);
    t4 = in_3_n1.^5;
    out_2 = t2.*t4+t3.*t4.*(in_1_n3.*in_2_n1+in_1_n4.*in_2_n2)-in_3_n1.^3.*t3.*(in_3_n3.*in_4_n1.*2.0+in_3_n4.*in_4_n2.*2.0).*1.0e+1-in_3_n1.^4.*t2.*(in_1_n3.*in_4_n1+in_2_n1.*in_3_n3+in_1_n4.*in_4_n2+in_2_n2.*in_3_n4).*5.0;
end
end

