function varargout=sym_MackeyGlass(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'npar'
   varargout{1}=4;
   return
  case 'nf'
   varargout{1}=1;
   return
  case 'nx'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  1  2];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_MackeyGlass_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function out_1 = sym_MackeyGlass_rhs_1_0(in1,in2,in3,in4)
%sym_MackeyGlass_rhs_1_0
%    OUT_1 = sym_MackeyGlass_rhs_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:03:50

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n4 = in2(:,4);
out_1 = -in_1_n1.*in_2_n4+(in_1_n2.*in_2_n1)./(in_1_n2.^in_2_n2+1.0);
end


function out_1 = sym_MackeyGlass_rhs_1_1(in1,in2,in3,in4)
%sym_MackeyGlass_rhs_1_1
%    OUT_1 = sym_MackeyGlass_rhs_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:03:50

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n4 = in2(:,4);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n4 = in4(:,4);
t2 = in_1_n2.^in_2_n2;
t3 = t2+1.0;
t4 = 1.0./t3;
out_1 = -in_1_n1.*in_4_n4-in_2_n4.*in_3_n1+in_1_n2.*in_4_n1.*t4+in_2_n1.*in_3_n2.*t4-in_1_n2.*in_2_n1.*t4.^2.*(in_4_n2.*t2.*log(in_1_n2)+in_1_n2.^(in_2_n2-1.0).*in_2_n2.*in_3_n2);
end


function out_1 = sym_MackeyGlass_rhs_1_2(in1,in2,in3,in4)
%sym_MackeyGlass_rhs_1_2
%    OUT_1 = sym_MackeyGlass_rhs_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:03:50

in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n4 = in4(:,4);
t2 = log(in_1_n2);
t3 = in_1_n2.^in_2_n2;
t4 = in_2_n2-1.0;
t5 = t3+1.0;
t6 = in_1_n2.^t4;
t7 = in_4_n2.*t2.*t3;
t8 = 1.0./t5.^2;
t9 = in_2_n2.*in_3_n2.*t6;
t10 = t7+t9;
out_1 = in_3_n1.*in_4_n4.*-2.0+(in_3_n2.*in_4_n1.*2.0)./t5-in_1_n2.*in_4_n1.*t8.*t10.*2.0-in_2_n1.*in_3_n2.*t8.*t10.*2.0+in_1_n2.*in_2_n1.*1.0./t5.^3.*t10.^2.*2.0-in_1_n2.*in_2_n1.*t8.*(in_2_n2.*in_3_n2.*(in_4_n2.*t2.*t6+in_1_n2.^(t4-1.0).*in_3_n2.*t4)+in_3_n2.*in_4_n2.*t6+in_4_n2.*t2.*t10+(in_3_n2.*in_4_n2.*t3)./in_1_n2);
end


function out_1 = sym_MackeyGlass_rhs_1_3(in1,in2,in3,in4)
%sym_MackeyGlass_rhs_1_3
%    OUT_1 = sym_MackeyGlass_rhs_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:03:50

in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
t2 = log(in_1_n2);
t3 = in_1_n2.^in_2_n2;
t4 = in_2_n2-1.0;
t6 = 1.0./in_1_n2;
t5 = t4-1.0;
t7 = t3+1.0;
t8 = in_1_n2.^t4;
t10 = in_4_n2.*t2.*t3;
t15 = in_3_n2.*in_4_n2.*t3.*t6;
t9 = in_1_n2.^t5;
t11 = 1.0./t7.^2;
t12 = 1.0./t7.^3;
t13 = in_2_n2.*in_3_n2.*t8;
t14 = in_3_n2.*in_4_n2.*t8;
t16 = in_4_n2.*t2.*t8;
t17 = in_3_n2.*t4.*t9;
t18 = t10+t13;
t19 = t18.^2;
t20 = in_4_n2.*t2.*t18;
t21 = t16+t17;
t22 = in_2_n2.*in_3_n2.*t21;
t23 = t14+t15+t20+t22;
out_1 = in_1_n2.*in_4_n1.*t12.*t19.*6.0+in_2_n1.*in_3_n2.*t12.*t19.*6.0-in_1_n2.*in_4_n1.*t11.*t23.*3.0-in_2_n1.*in_3_n2.*t11.*t23.*3.0-in_3_n2.*in_4_n1.*t11.*t18.*6.0-in_1_n2.*in_2_n1.*t11.*(in_2_n2.*in_3_n2.*(t6.*t14+in_3_n2.*t4.*(in_4_n2.*t2.*t9+in_1_n2.^(t5-1.0).*in_3_n2.*t5)+in_3_n2.*in_4_n2.*t9+in_4_n2.*t2.*t21)+in_3_n2.*in_4_n2.*t21.*2.0-in_3_n2.*t6.*t15+in_4_n2.*t2.*t23+in_3_n2.*in_4_n2.*t6.*t18.*2.0)-in_1_n2.*in_2_n1.*t11.^2.*t18.^3.*6.0+in_1_n2.*in_2_n1.*t12.*t18.*t23.*6.0;
end


function out_1 = sym_MackeyGlass_rhs_1_4(in1,in2,in3,in4)
%sym_MackeyGlass_rhs_1_4
%    OUT_1 = sym_MackeyGlass_rhs_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:03:50

in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
t2 = log(in_1_n2);
t3 = in_1_n2.^in_2_n2;
t4 = in_3_n2.^2;
t5 = in_2_n2-1.0;
t8 = 1.0./in_1_n2;
t6 = t5-1.0;
t9 = t8.^2;
t10 = t3+1.0;
t11 = in_1_n2.^t5;
t14 = in_4_n2.*t2.*t3;
t21 = in_3_n2.*in_4_n2.*t3.*t8;
t7 = t6-1.0;
t12 = in_1_n2.^t6;
t15 = 1.0./t10.^2;
t16 = 1.0./t10.^3;
t18 = in_2_n2.*in_3_n2.*t11;
t19 = in_3_n2.*in_4_n2.*t11;
t22 = in_4_n2.*t2.*t11;
t26 = in_4_n2.*t3.*t4.*t9;
t13 = in_1_n2.^t7;
t17 = t15.^2;
t20 = in_3_n2.*in_4_n2.*t12;
t23 = in_4_n2.*t2.*t12;
t24 = in_3_n2.*t5.*t12;
t27 = t8.*t19;
t28 = -t26;
t29 = t14+t18;
t25 = in_3_n2.*t6.*t13;
t30 = t29.^2;
t31 = t29.^3;
t32 = in_4_n2.*t2.*t29;
t33 = t22+t24;
t35 = in_3_n2.*in_4_n2.*t8.*t29.*2.0;
t34 = t23+t25;
t36 = in_2_n2.*in_3_n2.*t33;
t37 = in_4_n2.*t2.*t33;
t38 = in_3_n2.*in_4_n2.*t33.*2.0;
t39 = in_3_n2.*t5.*t34;
t40 = t19+t21+t32+t36;
t41 = in_4_n2.*t2.*t40;
t42 = t20+t27+t37+t39;
t43 = in_2_n2.*in_3_n2.*t42;
t44 = t28+t35+t38+t41+t43;
out_1 = in_1_n2.*in_4_n1.*t17.*t31.*-2.4e+1-in_2_n1.*in_3_n2.*t17.*t31.*2.4e+1-in_1_n2.*in_4_n1.*t15.*t44.*4.0-in_2_n1.*in_3_n2.*t15.*t44.*4.0+in_3_n2.*in_4_n1.*t16.*t30.*2.4e+1-in_3_n2.*in_4_n1.*t15.*t40.*1.2e+1+in_1_n2.*in_2_n1.*t16.*t40.^2.*6.0-in_1_n2.*in_2_n1.*t15.*(in_3_n2.^2.*t8.^2.*t21.*2.0+in_3_n2.*in_4_n2.*t42.*3.0+in_4_n2.*t2.*t44+in_2_n2.*in_3_n2.*(t8.*t38+in_3_n2.*t5.*(t8.*t20+in_3_n2.*t6.*(in_4_n2.*t2.*t13+in_1_n2.^(t7-1.0).*in_3_n2.*t7)+in_3_n2.*in_4_n2.*t13+in_4_n2.*t2.*t34)+in_3_n2.*in_4_n2.*t34.*2.0+in_4_n2.*t2.*t42-in_4_n2.*t4.*t9.*t11)+in_3_n2.*in_4_n2.*t8.*t40.*3.0-in_4_n2.*t4.*t9.*t29.*3.0)+in_1_n2.*in_2_n1.*1.0./t10.^5.*t30.^2.*2.4e+1-in_1_n2.*in_2_n1.*t17.*t30.*t40.*3.6e+1+in_1_n2.*in_2_n1.*t16.*t29.*t44.*8.0+in_1_n2.*in_4_n1.*t16.*t29.*t40.*2.4e+1+in_2_n1.*in_3_n2.*t16.*t29.*t40.*2.4e+1;
end


function out_1 = sym_MackeyGlass_rhs_1_5(in1,in2,in3,in4)
%sym_MackeyGlass_rhs_1_5
%    OUT_1 = sym_MackeyGlass_rhs_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:03:51

in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
t2 = log(in_1_n2);
t3 = in_1_n2.^in_2_n2;
t4 = in_3_n2.^2;
t5 = in_3_n2.^3;
t6 = in_2_n2-1.0;
t10 = 1.0./in_1_n2;
t7 = t6-1.0;
t11 = t10.^2;
t12 = t10.^3;
t13 = t3+1.0;
t14 = in_1_n2.^t6;
t18 = in_4_n2.*t2.*t3;
t27 = in_3_n2.*in_4_n2.*t3.*t10;
t8 = t7-1.0;
t15 = in_1_n2.^t7;
t19 = 1.0./t13.^2;
t20 = 1.0./t13.^3;
t22 = 1.0./t13.^5;
t23 = in_2_n2.*in_3_n2.*t14;
t24 = in_3_n2.*in_4_n2.*t14;
t28 = in_4_n2.*t2.*t14;
t34 = in_4_n2.*t3.*t4.*t11;
t37 = in_4_n2.*t3.*t5.*t12.*2.0;
t39 = in_4_n2.*t4.*t11.*t14;
t9 = t8-1.0;
t16 = in_1_n2.^t8;
t21 = t19.^2;
t25 = in_3_n2.*in_4_n2.*t15;
t29 = in_4_n2.*t2.*t15;
t31 = in_3_n2.*t6.*t15;
t35 = t10.*t24;
t38 = -t34;
t40 = -t39;
t41 = t18+t23;
t17 = in_1_n2.^t9;
t26 = in_3_n2.*in_4_n2.*t16;
t30 = in_4_n2.*t2.*t16;
t32 = in_3_n2.*t7.*t16;
t36 = t10.*t25;
t42 = t41.^2;
t43 = t41.^3;
t45 = in_4_n2.*t2.*t41;
t46 = t28+t31;
t49 = in_3_n2.*in_4_n2.*t10.*t41.*2.0;
t51 = in_4_n2.*t4.*t11.*t41.*3.0;
t33 = in_3_n2.*t8.*t17;
t44 = t42.^2;
t47 = t29+t32;
t50 = in_2_n2.*in_3_n2.*t46;
t52 = in_4_n2.*t2.*t46;
t54 = in_3_n2.*in_4_n2.*t46.*2.0;
t56 = -t51;
t48 = t30+t33;
t53 = in_4_n2.*t2.*t47;
t55 = in_3_n2.*in_4_n2.*t47.*2.0;
t57 = in_3_n2.*t6.*t47;
t59 = t10.*t54;
t60 = t24+t27+t45+t50;
t58 = in_3_n2.*t7.*t48;
t61 = t60.^2;
t62 = in_4_n2.*t2.*t60;
t63 = in_3_n2.*in_4_n2.*t10.*t60.*3.0;
t64 = t25+t35+t52+t57;
t65 = t26+t36+t53+t58;
t66 = in_2_n2.*in_3_n2.*t64;
t67 = in_3_n2.*in_4_n2.*t64.*3.0;
t68 = in_4_n2.*t2.*t64;
t69 = in_3_n2.*t6.*t65;
t70 = t38+t49+t54+t62+t66;
t71 = in_4_n2.*t2.*t70;
t72 = t40+t55+t59+t68+t69;
t73 = in_2_n2.*in_3_n2.*t72;
t74 = t37+t56+t63+t67+t71+t73;
et1 = in_1_n2.*in_4_n1.*t22.*t44.*1.2e+2+in_2_n1.*in_3_n2.*t22.*t44.*1.2e+2+in_1_n2.*in_4_n1.*t20.*t61.*3.0e+1+in_2_n1.*in_3_n2.*t20.*t61.*3.0e+1-in_3_n2.*in_4_n1.*t21.*t43.*1.2e+2-in_1_n2.*in_4_n1.*t19.*t74.*5.0-in_2_n1.*in_3_n2.*t19.*t74.*5.0-in_3_n2.*in_4_n1.*t19.*t70.*2.0e+1-in_1_n2.*in_2_n1.*t19.*(in_2_n2.*in_3_n2.*(t10.*t67+in_3_n2.*in_4_n2.*t65.*3.0+in_4_n2.*t2.*t72+in_3_n2.*t6.*(t10.*t55+in_3_n2.*t7.*(t10.*t26+in_3_n2.*t8.*(in_4_n2.*t2.*t17+in_1_n2.^(t9-1.0).*in_3_n2.*t9)+in_3_n2.*in_4_n2.*t17+in_4_n2.*t2.*t48)+in_3_n2.*in_4_n2.*t48.*2.0+in_4_n2.*t2.*t65-in_4_n2.*t4.*t11.*t15)+in_4_n2.*t5.*t12.*t14.*2.0-in_4_n2.*t4.*t11.*t46.*3.0)+in_3_n2.*in_4_n2.*t72.*4.0+in_4_n2.*t2.*t74-t4.*t11.*t34.*6.0+in_3_n2.*in_4_n2.*t10.*t70.*4.0+in_4_n2.*t5.*t12.*t41.*8.0-in_4_n2.*t4.*t11.*t60.*6.0)-in_1_n2.*in_2_n1.*t19.^3.*t41.^5.*1.2e+2;
et2 = in_1_n2.*in_2_n1.*t21.*t41.*t61.*-9.0e+1+in_1_n2.*in_2_n1.*t22.*t43.*t60.*2.4e+2-in_1_n2.*in_2_n1.*t21.*t42.*t70.*6.0e+1+in_1_n2.*in_2_n1.*t20.*t41.*t74.*1.0e+1-in_1_n2.*in_4_n1.*t21.*t42.*t60.*1.8e+2-in_2_n1.*in_3_n2.*t21.*t42.*t60.*1.8e+2+in_1_n2.*in_2_n1.*t20.*t60.*t70.*2.0e+1+in_1_n2.*in_4_n1.*t20.*t41.*t70.*4.0e+1+in_2_n1.*in_3_n2.*t20.*t41.*t70.*4.0e+1+in_3_n2.*in_4_n1.*t20.*t41.*t60.*1.2e+2;
out_1 = et1+et2;
end

