function varargout=sym_tor(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:9);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',6);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('sym_tor_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = sym_tor_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%SYM_TOR_RHS_0
%    [OUT1,OUT2,OUT3] = SYM_TOR_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Oct-2023 12:55:47

t2 = -in2;
t3 = in1+t2;
t4 = t3.^3;
t5 = in9.*t4;
out1 = -(t5+in5.*t2+in1.^3.*in8+in1.*(in4+in5))./in7;
if nargout > 1
    out2 = -in3+t5+t2.*(in5+in6)+in1.*in5;
end
if nargout > 2
    out3 = in2;
end
end


function [out1,out2,out3] = sym_tor_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%SYM_TOR_RHS_1
%    [OUT1,OUT2,OUT3] = SYM_TOR_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Oct-2023 12:55:47

t2 = in4+in5;
t3 = in1.^3;
t4 = -in2;
t5 = -in11;
t6 = in1+t4;
t7 = in10+t5;
t8 = t6.^2;
t9 = t6.^3;
t10 = in18.*t9;
t11 = in9.*t7.*t8.*3.0;
out1 = -(t10+t11+in5.*t5+in10.*t2+in14.*t4+in17.*t3+in1.*(in13+in14)+in1.^2.*in8.*in10.*3.0)./in7+1.0./in7.^2.*in16.*(in1.*t2+in5.*t4+in8.*t3+in9.*t9);
if nargout > 1
    out2 = -in12+t10+t11+t5.*(in5+in6)+t4.*(in14+in15)+in1.*in14+in5.*in10;
end
if nargout > 2
    out3 = in11;
end
end


function [out1,out2,out3] = sym_tor_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18)
%SYM_TOR_RHS_2
%    [OUT1,OUT2,OUT3] = SYM_TOR_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Oct-2023 12:55:47

t2 = in4+in5;
t3 = in13+in14;
t4 = in1.^2;
t5 = in1.^3;
t6 = -in2;
t7 = -in11;
t8 = in1+t6;
t9 = in10+t7;
t10 = t8.^2;
t11 = t8.^3;
t12 = t9.^2;
t13 = in9.*t8.*t12.*6.0;
t14 = in18.*t9.*t10.*6.0;
out1 = -(t13+t14-in11.*in14.*2.0+in10.*t3.*2.0+in10.*in17.*t4.*6.0+in1.*in8.*in10.^2.*6.0)./in7-1.0./in7.^3.*in16.^2.*(in1.*t2+in5.*t6+in8.*t5+in9.*t11).*2.0+1.0./in7.^2.*in16.*(in1.*t3+in5.*t7+in10.*t2+in14.*t6+in17.*t5+in18.*t11+in8.*in10.*t4.*3.0+in9.*t9.*t10.*3.0).*2.0;
if nargout > 1
    out2 = t13+t14+in10.*in14.*2.0-in11.*(in14+in15).*2.0;
end
if nargout > 2
    out3 = 0.0;
end
end

