function varargout=sym_HollingTanner(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'npar'
   varargout{1}=6;
   return
  case 'nf'
   varargout{1}=2;
   return
  case 'nx'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1  1  2  2  2];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_HollingTanner_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2] = sym_HollingTanner_rhs_1_0(in1,in2,in3,in4)
%sym_HollingTanner_rhs_1_0
%    [OUT_1,OUT_2] = sym_HollingTanner_rhs_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Jul-2024 23:42:53

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
t2 = in_1_n1+in_2_n4;
out_1 = -in_2_n5-t2.*(t2-1.0)-(in_1_n1.*in_1_n2)./(in_1_n1+in_1_n2.*in_2_n3);
if nargout > 1
    out_2 = in_1_n2.*in_2_n6.*(in_2_n1-in_1_n4./in_1_n3);
end
end


function [out_1,out_2] = sym_HollingTanner_rhs_1_1(in1,in2,in3,in4)
%sym_HollingTanner_rhs_1_1
%    [OUT_1,OUT_2] = sym_HollingTanner_rhs_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Jul-2024 23:42:53

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
t2 = in_1_n2.*in_2_n3;
t3 = in_3_n1+in_4_n4;
t4 = 1.0./in_1_n3;
t5 = in_1_n1+t2;
t6 = in_1_n4.*t4;
t7 = 1.0./t5;
out_1 = -in_4_n5-t3.*(in_1_n1+in_2_n4)-t3.*(in_1_n1+in_2_n4-1.0)-in_1_n1.*in_3_n2.*t7-in_1_n2.*in_3_n1.*t7+in_1_n1.*in_1_n2.*t7.^2.*(in_3_n1+in_1_n2.*in_4_n3+in_2_n3.*in_3_n2);
if nargout > 1
    t8 = -t6;
    t9 = in_2_n1+t8;
    out_2 = in_1_n2.*in_4_n6.*t9+in_2_n6.*in_3_n2.*t9+in_1_n2.*in_2_n6.*(in_4_n1-in_3_n4.*t4+in_3_n3.*t4.*t6);
end
end


function [out_1,out_2] = sym_HollingTanner_rhs_1_2(in1,in2,in3,in4)
%sym_HollingTanner_rhs_1_2
%    [OUT_1,OUT_2] = sym_HollingTanner_rhs_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Jul-2024 23:42:53

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n3 = in2(:,3);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n6 = in4(:,6);
t2 = in_1_n2.*in_2_n3;
t3 = in_1_n2.*in_4_n3;
t4 = in_2_n3.*in_3_n2;
t5 = 1.0./in_1_n3;
t6 = t5.^2;
t7 = in_1_n1+t2;
t8 = in_3_n4.*t5;
t10 = in_3_n1+t3+t4;
t9 = in_1_n4.*in_3_n3.*t6;
t11 = 1.0./t7.^2;
out_1 = (in_3_n1+in_4_n4).^2.*-2.0-(in_3_n1.*in_3_n2.*2.0)./t7+in_1_n1.*in_3_n2.*t3.*t11.*2.0+in_1_n1.*in_3_n2.*t10.*t11.*2.0+in_1_n2.*in_3_n1.*t10.*t11.*2.0-in_1_n1.*in_1_n2.*1.0./t7.^3.*t10.^2.*2.0;
if nargout > 1
    t12 = -t8;
    t13 = in_4_n1+t9+t12;
    out_2 = in_3_n2.*in_4_n6.*(in_2_n1-in_1_n4.*t5).*2.0-in_1_n2.*in_2_n6.*(in_1_n4.*in_3_n3.^2.*t5.^3.*2.0-in_3_n3.*in_3_n4.*t6.*2.0)+in_1_n2.*in_4_n6.*t13.*2.0+in_2_n6.*in_3_n2.*t13.*2.0;
end
end


function [out_1,out_2] = sym_HollingTanner_rhs_1_3(in1,in2,in3,in4)
%sym_HollingTanner_rhs_1_3
%    [OUT_1,OUT_2] = sym_HollingTanner_rhs_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Jul-2024 23:42:53

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n3 = in2(:,3);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n3 = in4(:,3);
in_4_n6 = in4(:,6);
t2 = in_1_n2.*in_2_n3;
t3 = in_1_n2.*in_4_n3;
t4 = in_2_n3.*in_3_n2;
t5 = in_3_n3.^2;
t6 = 1.0./in_1_n3.^2;
t7 = 1.0./in_1_n3.^3;
t8 = in_1_n1+t2;
t9 = in_3_n1+t3+t4;
t12 = in_3_n3.*in_3_n4.*t6.*2.0;
t14 = in_1_n4.*t5.*t7.*2.0;
t10 = 1.0./t8.^2;
t11 = 1.0./t8.^3;
t15 = t9.^2;
out_1 = in_1_n1.*in_3_n2.*t11.*t15.*-6.0-in_1_n2.*in_3_n1.*t11.*t15.*6.0+in_3_n1.*in_3_n2.*t3.*t10.*6.0+in_3_n1.*in_3_n2.*t9.*t10.*6.0+in_1_n1.*in_3_n2.^2.*in_4_n3.*t10.*6.0+in_1_n1.*in_1_n2.*t9.^3.*t10.^2.*6.0-in_1_n1.*in_3_n2.*t3.*t9.*t11.*1.2e+1;
if nargout > 1
    out_2 = in_3_n2.*in_4_n6.*(in_4_n1-in_3_n4./in_1_n3+in_1_n4.*in_3_n3.*t6).*6.0+in_1_n2.*in_2_n6.*(in_1_n4.*in_3_n3.^3.*t6.^2.*6.0-in_3_n4.*t5.*t7.*6.0)+in_1_n2.*in_4_n6.*(t12-t14).*3.0+in_2_n6.*in_3_n2.*(t12-t14).*3.0;
end
end


function [out_1,out_2] = sym_HollingTanner_rhs_1_4(in1,in2,in3,in4)
%sym_HollingTanner_rhs_1_4
%    [OUT_1,OUT_2] = sym_HollingTanner_rhs_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Jul-2024 23:42:54

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n3 = in2(:,3);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n3 = in4(:,3);
in_4_n6 = in4(:,6);
t2 = in_1_n2.*in_2_n3;
t3 = in_1_n2.*in_4_n3;
t4 = in_2_n3.*in_3_n2;
t5 = in_3_n2.^2;
t6 = in_3_n3.^2;
t7 = in_3_n3.^3;
t8 = 1.0./in_1_n3.^3;
t9 = 1.0./in_1_n3.^4;
t10 = in_1_n1+t2;
t11 = in_3_n1+t3+t4;
t14 = in_1_n4.*t7.*t9.*6.0;
t15 = in_3_n4.*t6.*t8.*6.0;
t12 = 1.0./t10.^3;
t13 = 1.0./t10.^4;
t16 = t11.^2;
t17 = t11.^3;
out_1 = in_1_n1.*in_3_n2.*t13.*t17.*2.4e+1+in_1_n2.*in_3_n1.*t13.*t17.*2.4e+1-in_3_n1.*in_3_n2.*t12.*t16.*2.4e+1+in_3_n1.*in_4_n3.*t5.*1.0./t10.^2.*2.4e+1-in_1_n1.*in_1_n2.*1.0./t10.^5.*t16.^2.*2.4e+1-in_1_n1.*in_4_n3.*t3.*t5.*t12.*2.4e+1+in_1_n1.*in_3_n2.*t3.*t13.*t16.*7.2e+1-in_1_n1.*in_4_n3.*t5.*t11.*t12.*4.8e+1-in_3_n1.*in_3_n2.*t3.*t11.*t12.*4.8e+1;
if nargout > 1
    t18 = -t15;
    t19 = t14+t18;
    out_2 = in_3_n2.*in_4_n6.*(in_1_n4.*t6.*t8.*2.0-1.0./in_1_n3.^2.*in_3_n3.*in_3_n4.*2.0).*-1.2e+1+in_1_n2.*in_4_n6.*t19.*4.0+in_2_n6.*in_3_n2.*t19.*4.0-in_1_n2.*in_2_n6.*(1.0./in_1_n3.^5.*in_1_n4.*t6.^2.*2.4e+1-in_3_n4.*t7.*t9.*2.4e+1);
end
end


function [out_1,out_2] = sym_HollingTanner_rhs_1_5(in1,in2,in3,in4)
%sym_HollingTanner_rhs_1_5
%    [OUT_1,OUT_2] = sym_HollingTanner_rhs_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Jul-2024 23:42:54

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n3 = in2(:,3);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n3 = in4(:,3);
in_4_n6 = in4(:,6);
t2 = in_1_n2.*in_2_n3;
t3 = in_1_n2.*in_4_n3;
t4 = in_2_n3.*in_3_n2;
t5 = in_3_n2.^2;
t6 = in_3_n3.^3;
t7 = in_3_n3.^4;
t8 = in_4_n3.^2;
t9 = 1.0./in_1_n3.^4;
t10 = 1.0./in_1_n3.^5;
t11 = in_1_n1+t2;
t12 = in_3_n1+t3+t4;
t19 = in_1_n4.*t7.*t10.*2.4e+1;
t20 = in_3_n4.*t6.*t9.*2.4e+1;
t13 = 1.0./t11.^3;
t14 = 1.0./t11.^4;
t15 = 1.0./t11.^5;
t16 = t12.^2;
t17 = t12.^3;
t21 = -t20;
t18 = t16.^2;
out_1 = in_1_n1.*in_3_n2.*t15.*t18.*-1.2e+2-in_1_n2.*in_3_n1.*t15.*t18.*1.2e+2+in_3_n1.*in_3_n2.*t14.*t17.*1.2e+2-in_1_n1.*in_3_n2.^3.*t8.*t13.*1.2e+2+in_1_n1.*in_1_n2.*t12.^5.*t13.^2.*1.2e+2-in_1_n1.*in_3_n2.*t3.*t15.*t17.*4.8e+2+in_1_n1.*in_4_n3.*t5.*t14.*t16.*3.6e+2-in_3_n1.*in_4_n3.*t3.*t5.*t13.*1.2e+2+in_3_n1.*in_3_n2.*t3.*t14.*t16.*3.6e+2-in_3_n1.*in_4_n3.*t5.*t12.*t13.*2.4e+2+in_1_n1.*in_4_n3.*t3.*t5.*t12.*t14.*3.6e+2;
if nargout > 1
    t22 = t19+t21;
    out_2 = in_3_n2.*in_4_n6.*(1.0./in_1_n3.^3.*in_3_n3.^2.*in_3_n4.*6.0-in_1_n4.*t6.*t9.*6.0).*-2.0e+1+in_1_n2.*in_2_n6.*(1.0./in_1_n3.^6.*in_1_n4.*in_3_n3.^5.*1.2e+2-in_3_n4.*t7.*t10.*1.2e+2)-in_1_n2.*in_4_n6.*t22.*5.0-in_2_n6.*in_3_n2.*t22.*5.0;
end
end

