function varargout=sym_stst(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=0;
   return
  case 'npar'
   varargout{1}=12;
   return
  case 'nf'
   varargout{1}=4;
   return
  case 'nx'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=1;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_stst_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2,out_3,out_4] = sym_stst_rhs_1_0(in_1_n1,in2,in_3_n1,in4)
%SYM_STST_RHS_1_0
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_STST_RHS_1_0(IN_1_N1,IN2,IN_3_N1,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:41

in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_2_n9 = in2(:,9);
in_2_n10 = in2(:,10);
in_2_n11 = in2(:,11);
t2 = in_1_n1.*in_2_n5;
t3 = in_2_n4+in_2_n8;
t6 = in_2_n1.^2;
t7 = in_2_n3.^2;
t12 = -in_2_n2;
t13 = 1.0./in_2_n5;
t14 = 1.0./in_2_n6;
t15 = 1.0./in_2_n8;
t16 = 1.0./in_2_n9;
t9 = in_2_n1.*t2;
t10 = in_2_n2.*t2;
t11 = in_2_n3.*t2;
t17 = t2+1.0;
t18 = in_2_n4+t3;
t19 = in_1_n1.*t16;
t20 = 1.0./t3;
t23 = t2.*t6.*2.0;
t28 = t2.^2.*t6;
t29 = t2.^2.*t7;
t21 = -t10;
t22 = -t11;
t24 = 1.0./t17.^3;
t25 = 1.0./t18;
t26 = t19-1.0;
t27 = in_2_n1+t9+t11;
t32 = -t29;
t30 = in_2_n1+t9+t22;
t31 = t27.^2;
t35 = t12+t21+t27;
t36 = t6+t23+t28+t32;
t33 = t30.^2;
t34 = 1.0./t30;
out_1 = -log(-t34.*t35)./(in_2_n4.*in_2_n11);
if nargout > 1
    out_2 = (in_2_n7.*in_2_n10.*t13.*t14.*t17.*t26)./(in_2_n7.*t2.*t24.*(t15.*t31.*exp(-in_2_n8.*in_2_n11)+t20.*t36.*exp(-in_2_n11.*t3).*2.0+t25.*t33.*exp(-in_2_n11.*t18))-in_2_n7.*t2.*t24.*(t15.*t31+t20.*t36.*2.0+t25.*t33));
end
if nargout > 2
    out_3 = -in_2_n7.*in_2_n10.*t13.*t14.*t17.*t26;
end
if nargout > 3
    out_4 = in_2_n2+in_2_n1.*t34.*t35;
end
end


function [out_1,out_2,out_3,out_4] = sym_stst_rhs_1_1(in_1_n1,in2,in_3_n1,in4)
%SYM_STST_RHS_1_1
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_STST_RHS_1_1(IN_1_N1,IN2,IN_3_N1,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:41

in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_2_n9 = in2(:,9);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
in_4_n9 = in4(:,9);
in_2_n10 = in2(:,10);
in_2_n11 = in2(:,11);
in_4_n10 = in4(:,10);
in_4_n11 = in4(:,11);
t2 = in_1_n1.*in_2_n5;
t3 = in_1_n1.*in_4_n5;
t4 = in_2_n5.*in_3_n1;
t5 = in_2_n8.*in_2_n11;
t6 = in_2_n4+in_2_n8;
t7 = in_4_n4+in_4_n8;
t11 = in_2_n1.^2;
t12 = in_2_n3.^2;
t13 = in_2_n5.^2;
t14 = in_2_n1.*in_4_n1.*2.0;
t27 = -in_2_n2;
t28 = -in_4_n2;
t29 = 1.0./in_2_n4;
t30 = 1.0./in_2_n5;
t32 = 1.0./in_2_n6;
t34 = 1.0./in_2_n8;
t36 = 1.0./in_2_n9;
t38 = 1.0./in_2_n11;
t15 = in_2_n1.*t2;
t16 = in_2_n2.*t2;
t17 = in_2_n3.*t2;
t18 = in_2_n1.*t3;
t19 = in_4_n1.*t2;
t20 = in_2_n1.*t4;
t21 = in_2_n2.*t3;
t22 = in_4_n2.*t2;
t23 = in_2_n2.*t4;
t24 = in_2_n3.*t3;
t25 = in_4_n3.*t2;
t26 = in_2_n3.*t4;
t31 = 1.0./t13;
t33 = t32.^2;
t35 = t34.^2;
t37 = t36.^2;
t39 = -t5;
t40 = t2+1.0;
t41 = in_2_n4+t6;
t42 = in_4_n4+t7;
t43 = in_2_n11.*t6;
t45 = in_1_n1.*t36;
t46 = in_3_n1.*t36;
t47 = 1.0./t6;
t59 = t3+t4;
t61 = t2.*t11.*2.0;
t62 = t3.*t11.*2.0;
t63 = t4.*t11.*2.0;
t74 = t2.^2.*t11;
t75 = t2.^2.*t12;
t78 = t2.*t4.*t12.*2.0;
t79 = t2.^2.*t14;
t82 = t2.*t3.*t12.*2.0;
t44 = in_4_n1.*t15.*4.0;
t48 = t47.^2;
t49 = exp(t39);
t50 = -t16;
t51 = -t17;
t52 = -t21;
t53 = -t22;
t54 = -t23;
t55 = -t24;
t56 = -t25;
t57 = -t26;
t58 = in_2_n11.*t41;
t60 = -t43;
t64 = in_1_n1.*in_4_n9.*t37;
t66 = 1.0./t40.^3;
t67 = 1.0./t40.^4;
t68 = 1.0./t41;
t71 = t45-1.0;
t73 = in_2_n1+t15+t17;
t77 = t4.*t61;
t80 = t17.*t25.*2.0;
t81 = t3.*t61;
t83 = -t78;
t85 = -t82;
t88 = -t75;
t97 = in_4_n1+t18+t19+t20+t24+t25+t26;
t65 = exp(t60);
t69 = t68.^2;
t70 = -t58;
t72 = -t64;
t84 = -t80;
t86 = in_2_n1+t15+t51;
t87 = t73.^2;
t94 = t27+t50+t73;
t98 = in_4_n1+t18+t19+t20+t55+t56+t57;
t100 = t11+t61+t74+t88;
t105 = t28+t52+t53+t54+t97;
t76 = exp(t70);
t89 = t86.^2;
t90 = 1.0./t86;
t92 = t46+t72;
t93 = t34.*t87;
t104 = t47.*t100.*2.0;
t108 = t14+t44+t62+t63+t77+t79+t81+t83+t84+t85;
t91 = 1.0./t89;
t95 = t49.*t93;
t96 = t68.*t89;
t101 = t90.*t94;
t106 = t65.*t104;
t99 = t76.*t96;
t102 = -t101;
t107 = t93+t96+t104;
t103 = log(t102);
out_1 = in_4_n4.*t29.^2.*t38.*t103+in_4_n11.*t29.*t38.^2.*t103-(t29.*t38.*t86.*(t90.*t105-t91.*t94.*t98))./t94;
if nargout > 1
    t109 = in_2_n7.*t2.*t66.*t107;
    t111 = t95+t99+t106;
    t112 = in_2_n7.*t2.*t66.*t111;
    t114 = -1.0./(t109-t112);
    et1 = in_2_n7.*in_2_n10.*t30.*t32.*t59.*t71.*t114+in_4_n7.*in_2_n10.*t30.*t32.*t40.*t71.*t114+in_2_n7.*in_2_n10.*t30.*t32.*t40.*t92.*t114+in_2_n7.*in_4_n10.*t30.*t32.*t40.*t71.*t114;
    et2 = in_2_n7.*in_2_n10.*t30.*t32.*t40.*t71.*1.0./(t109-t112).^2.*(in_2_n7.*t3.*t66.*t107+in_2_n7.*t4.*t66.*t107-in_2_n7.*t3.*t66.*t111-in_2_n7.*t4.*t66.*t111+in_4_n7.*t2.*t66.*t107-in_4_n7.*t2.*t66.*t111+in_2_n7.*t2.*t66.*(t95.*(in_4_n8.*in_2_n11+in_2_n8.*in_4_n11)+t106.*(in_2_n11.*t7+in_4_n11.*t6)+t99.*(in_2_n11.*t42+in_4_n11.*t41)-t47.*t65.*t108.*2.0+in_4_n8.*t35.*t49.*t87+t7.*t48.*t65.*t100.*2.0-t34.*t49.*t73.*t97.*2.0+t42.*t69.*t76.*t89-t68.*t76.*t86.*t98.*2.0)+in_2_n7.*t2.*t66.*(t47.*t108.*2.0-in_4_n8.*t35.*t87-t7.*t48.*t100.*2.0-t42.*t69.*t89+t34.*t73.*t97.*2.0+t68.*t86.*t98.*2.0)-in_2_n7.*t2.*t59.*t67.*t107.*3.0+in_2_n7.*t2.*t59.*t67.*t111.*3.0)+(in_2_n7.*in_4_n5.*in_2_n10.*t31.*t32.*t40.*t71)./(t109-t112);
    et3 = (in_2_n7.*in_4_n6.*in_2_n10.*t30.*t33.*t40.*t71)./(t109-t112);
    out_2 = et1+et2+et3;
end
if nargout > 2
    out_3 = -in_2_n7.*in_2_n10.*t30.*t32.*t59.*t71-in_4_n7.*in_2_n10.*t30.*t32.*t40.*t71-in_2_n7.*in_2_n10.*t30.*t32.*t40.*t92-in_2_n7.*in_4_n10.*t30.*t32.*t40.*t71+in_2_n7.*in_4_n5.*in_2_n10.*t31.*t32.*t40.*t71+in_2_n7.*in_4_n6.*in_2_n10.*t30.*t33.*t40.*t71;
end
if nargout > 3
    out_4 = in_4_n2+in_4_n1.*t101+in_2_n1.*t90.*t105-in_2_n1.*t91.*t94.*t98;
end
end

