function varargout=sym_ceff_int(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=0;
   return
  case 'npar'
   varargout{1}=5;
   return
  case 'nf'
   varargout{1}=1;
   return
  case 'nx'
   varargout{1}=4;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=3;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1  3  1  4  1];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_ceff_int_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function out_1 = sym_ceff_int_rhs_1_0(in1,in2,in3,in4)
%SYM_CEFF_INT_RHS_1_0
%    OUT_1 = SYM_CEFF_INT_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:38

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
t2 = in_1_n2.*in_2_n3;
out_1 = (in_1_n3.*in_2_n4.*t2.*exp(-in_1_n1.*in_2_n5).*(in_1_n4+in_2_n1.*exp(-in_1_n1.*in_2_n2)).^2)./(t2+1.0);
end


function out_1 = sym_ceff_int_rhs_1_1(in1,in2,in3,in4)
%SYM_CEFF_INT_RHS_1_1
%    OUT_1 = SYM_CEFF_INT_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:38

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
t2 = in_1_n1.*in_2_n2;
t3 = in_1_n2.*in_2_n3;
t4 = in_1_n1.*in_2_n5;
t5 = -t2;
t6 = -t4;
t7 = t3+1.0;
t8 = exp(t5);
t9 = exp(t6);
t11 = 1.0./t7;
t10 = in_2_n1.*t8;
t12 = in_1_n4+t10;
t13 = t12.^2;
out_1 = in_1_n3.*in_4_n4.*t3.*t9.*t11.*t13+in_2_n4.*in_3_n3.*t3.*t9.*t11.*t13-in_1_n3.*in_2_n4.*t3.*t9.*t11.^2.*t13.*(in_1_n2.*in_4_n3+in_2_n3.*in_3_n2)+in_1_n2.*in_1_n3.*in_2_n4.*in_4_n3.*t9.*t11.*t13+in_1_n3.*in_2_n3.*in_2_n4.*in_3_n2.*t9.*t11.*t13+in_1_n3.*in_2_n4.*t3.*t9.*t11.*t12.*(in_3_n4+in_4_n1.*t8-t10.*(in_1_n1.*in_4_n2+in_2_n2.*in_3_n1)).*2.0-in_1_n3.*in_2_n4.*t3.*t9.*t11.*t13.*(in_1_n1.*in_4_n5+in_2_n5.*in_3_n1);
end


function out_1 = sym_ceff_int_rhs_1_2(in1,in2,in3,in4)
%SYM_CEFF_INT_RHS_1_2
%    OUT_1 = SYM_CEFF_INT_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:38

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
t2 = in_1_n1.*in_2_n2;
t3 = in_1_n2.*in_2_n3;
t4 = in_1_n1.*in_2_n5;
t5 = in_1_n1.*in_4_n2;
t6 = in_2_n2.*in_3_n1;
t7 = in_1_n2.*in_4_n3;
t8 = in_2_n3.*in_3_n2;
t9 = in_1_n1.*in_4_n5;
t10 = in_2_n5.*in_3_n1;
t11 = -t2;
t12 = -t4;
t13 = t3+1.0;
t16 = t5+t6;
t17 = t7+t8;
t18 = t9+t10;
t14 = exp(t11);
t15 = exp(t12);
t21 = 1.0./t13;
t19 = in_2_n1.*t14;
t20 = in_4_n1.*t14;
t22 = t21.^2;
t23 = in_1_n4+t19;
t25 = t16.*t19;
t24 = t23.^2;
t26 = -t25;
t27 = in_3_n4+t20+t26;
et1 = in_1_n3.*in_4_n4.*t7.*t15.*t21.*t24.*2.0+in_2_n4.*in_3_n3.*t7.*t15.*t21.*t24.*2.0+in_1_n3.*in_4_n4.*t8.*t15.*t21.*t24.*2.0+in_2_n4.*in_3_n3.*t8.*t15.*t21.*t24.*2.0+in_3_n3.*in_4_n4.*t3.*t15.*t21.*t24.*2.0+in_1_n3.*in_2_n4.*t3.*t15.*t21.*t27.^2.*2.0+in_1_n3.*in_2_n4.*t3.*t15.*t17.^2.*t21.^3.*t24.*2.0+in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t15.*t21.*t24.*2.0-in_1_n3.*in_2_n4.*t7.*t15.*t17.*t22.*t24.*2.0-in_1_n3.*in_2_n4.*t7.*t15.*t18.*t21.*t24.*2.0-in_1_n3.*in_2_n4.*t8.*t15.*t17.*t22.*t24.*2.0-in_1_n3.*in_2_n4.*t8.*t15.*t18.*t21.*t24.*2.0+in_1_n3.*in_2_n4.*t7.*t15.*t21.*t23.*t27.*4.0+in_1_n3.*in_2_n4.*t8.*t15.*t21.*t23.*t27.*4.0-in_1_n3.*in_4_n4.*t3.*t15.*t17.*t22.*t24.*2.0-in_1_n3.*in_4_n4.*t3.*t15.*t18.*t21.*t24.*2.0-in_2_n4.*in_3_n3.*t3.*t15.*t17.*t22.*t24.*2.0-in_2_n4.*in_3_n3.*t3.*t15.*t18.*t21.*t24.*2.0+in_1_n3.*in_4_n4.*t3.*t15.*t21.*t23.*t27.*4.0+in_2_n4.*in_3_n3.*t3.*t15.*t21.*t23.*t27.*4.0;
et2 = in_1_n3.*in_2_n4.*t3.*t15.*t21.*t23.*(t16.*t20.*2.0+t16.*t26+in_3_n1.*in_4_n2.*t19.*2.0).*-2.0+in_1_n3.*in_2_n4.*t3.*t15.*t18.^2.*t21.*t24-in_1_n3.*in_2_n4.*in_3_n1.*in_4_n5.*t3.*t15.*t21.*t24.*2.0-in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t3.*t15.*t22.*t24.*2.0+in_1_n3.*in_2_n4.*t3.*t15.*t17.*t18.*t22.*t24.*2.0-in_1_n3.*in_2_n4.*t3.*t15.*t17.*t22.*t23.*t27.*4.0-in_1_n3.*in_2_n4.*t3.*t15.*t18.*t21.*t23.*t27.*4.0;
out_1 = et1+et2;
end


function out_1 = sym_ceff_int_rhs_1_3(in1,in2,in3,in4)
%SYM_CEFF_INT_RHS_1_3
%    OUT_1 = SYM_CEFF_INT_RHS_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:38

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
t2 = in_1_n1.*in_2_n2;
t3 = in_1_n2.*in_2_n3;
t4 = in_1_n1.*in_2_n5;
t5 = in_1_n1.*in_4_n2;
t6 = in_2_n2.*in_3_n1;
t7 = in_1_n2.*in_4_n3;
t8 = in_2_n3.*in_3_n2;
t9 = in_1_n1.*in_4_n5;
t10 = in_2_n5.*in_3_n1;
t11 = -t2;
t12 = -t4;
t13 = t3+1.0;
t16 = t5+t6;
t17 = t7+t8;
t18 = t9+t10;
t14 = exp(t11);
t15 = exp(t12);
t21 = 1.0./t13;
t24 = t16.^2;
t25 = t17.^2;
t26 = t18.^2;
t19 = in_2_n1.*t14;
t20 = in_4_n1.*t14;
t22 = t21.^2;
t23 = t21.^3;
t27 = in_1_n4+t19;
t28 = in_3_n1.*in_4_n2.*t19.*2.0;
t30 = t16.*t19;
t31 = t16.*t20.*2.0;
t33 = t19.*t24;
t29 = t27.^2;
t32 = -t30;
t34 = -t33;
t35 = in_3_n4+t20+t32;
t37 = t28+t31+t34;
t36 = t35.^2;
et1 = in_1_n3.*in_2_n4.*t7.*t15.*t21.*t36.*6.0+in_1_n3.*in_2_n4.*t8.*t15.*t21.*t36.*6.0+in_1_n3.*in_4_n4.*t3.*t15.*t21.*t36.*6.0+in_2_n4.*in_3_n3.*t3.*t15.*t21.*t36.*6.0+in_3_n3.*in_4_n4.*t7.*t15.*t21.*t29.*6.0+in_3_n3.*in_4_n4.*t8.*t15.*t21.*t29.*6.0-in_1_n3.*in_2_n4.*t3.*t15.*t17.^3.*t22.^2.*t29.*6.0+in_1_n3.*in_3_n2.*in_4_n3.*in_4_n4.*t15.*t21.*t29.*6.0+in_2_n4.*in_3_n2.*in_3_n3.*in_4_n3.*t15.*t21.*t29.*6.0-in_1_n3.*in_2_n4.*t3.*t15.*t17.*t22.*t36.*6.0-in_1_n3.*in_2_n4.*t3.*t15.*t18.*t21.*t36.*6.0+in_1_n3.*in_2_n4.*t7.*t15.*t21.*t26.*t29.*3.0+in_1_n3.*in_2_n4.*t7.*t15.*t23.*t25.*t29.*6.0+in_1_n3.*in_2_n4.*t8.*t15.*t21.*t26.*t29.*3.0+in_1_n3.*in_2_n4.*t8.*t15.*t23.*t25.*t29.*6.0-in_1_n3.*in_2_n4.*t7.*t15.*t21.*t27.*t37.*6.0-in_1_n3.*in_2_n4.*t8.*t15.*t21.*t27.*t37.*6.0-in_1_n3.*in_4_n4.*t7.*t15.*t17.*t22.*t29.*6.0-in_1_n3.*in_4_n4.*t7.*t15.*t18.*t21.*t29.*6.0-in_2_n4.*in_3_n3.*t7.*t15.*t17.*t22.*t29.*6.0-in_2_n4.*in_3_n3.*t7.*t15.*t18.*t21.*t29.*6.0;
et2 = in_1_n3.*in_2_n4.*t3.*t15.*t21.*t35.*t37.*-6.0-in_1_n3.*in_4_n4.*t8.*t15.*t17.*t22.*t29.*6.0-in_1_n3.*in_4_n4.*t8.*t15.*t18.*t21.*t29.*6.0-in_2_n4.*in_3_n3.*t8.*t15.*t17.*t22.*t29.*6.0-in_2_n4.*in_3_n3.*t8.*t15.*t18.*t21.*t29.*6.0+in_1_n3.*in_4_n4.*t3.*t15.*t21.*t26.*t29.*3.0+in_2_n4.*in_3_n3.*t3.*t15.*t21.*t26.*t29.*3.0+in_1_n3.*in_4_n4.*t3.*t15.*t23.*t25.*t29.*6.0+in_2_n4.*in_3_n3.*t3.*t15.*t23.*t25.*t29.*6.0-in_1_n3.*in_4_n4.*t3.*t15.*t21.*t27.*t37.*6.0-in_2_n4.*in_3_n3.*t3.*t15.*t21.*t27.*t37.*6.0+in_1_n3.*in_4_n4.*t7.*t15.*t21.*t27.*t35.*1.2e+1+in_2_n4.*in_3_n3.*t7.*t15.*t21.*t27.*t35.*1.2e+1+in_1_n3.*in_4_n4.*t8.*t15.*t21.*t27.*t35.*1.2e+1+in_2_n4.*in_3_n3.*t8.*t15.*t21.*t27.*t35.*1.2e+1-in_3_n3.*in_4_n4.*t3.*t15.*t17.*t22.*t29.*6.0-in_3_n3.*in_4_n4.*t3.*t15.*t18.*t21.*t29.*6.0+in_3_n3.*in_4_n4.*t3.*t15.*t21.*t27.*t35.*1.2e+1;
et3 = in_1_n3.*in_2_n4.*t3.*t15.*t21.*t27.*(t20.*t24.*3.0+t16.^2.*t32-in_3_n1.*in_4_n2.*t20.*6.0+in_3_n1.*in_4_n2.*t30.*6.0).*2.0-in_1_n3.*in_2_n4.*t3.*t15.*t18.^3.*t21.*t29-in_1_n3.*in_2_n4.*in_3_n1.*in_4_n5.*t7.*t15.*t21.*t29.*6.0-in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t7.*t15.*t22.*t29.*6.0-in_1_n3.*in_2_n4.*in_3_n1.*in_4_n5.*t8.*t15.*t21.*t29.*6.0-in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t8.*t15.*t22.*t29.*6.0-in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t15.*t17.*t22.*t29.*6.0-in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t15.*t18.*t21.*t29.*6.0-in_1_n3.*in_3_n1.*in_4_n4.*in_4_n5.*t3.*t15.*t21.*t29.*6.0-in_1_n3.*in_3_n2.*in_4_n3.*in_4_n4.*t3.*t15.*t22.*t29.*6.0-in_2_n4.*in_3_n1.*in_3_n3.*in_4_n5.*t3.*t15.*t21.*t29.*6.0-in_2_n4.*in_3_n2.*in_3_n3.*in_4_n3.*t3.*t15.*t22.*t29.*6.0+in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t15.*t21.*t27.*t35.*1.2e+1+in_1_n3.*in_2_n4.*t7.*t15.*t17.*t18.*t22.*t29.*6.0+in_1_n3.*in_2_n4.*t8.*t15.*t17.*t18.*t22.*t29.*6.0-in_1_n3.*in_2_n4.*t3.*t15.*t17.*t22.*t26.*t29.*3.0;
et4 = in_1_n3.*in_2_n4.*t3.*t15.*t18.*t23.*t25.*t29.*-6.0+in_1_n3.*in_2_n4.*t3.*t15.*t17.*t22.*t27.*t37.*6.0+in_1_n3.*in_2_n4.*t3.*t15.*t18.*t21.*t27.*t37.*6.0-in_1_n3.*in_2_n4.*t7.*t15.*t17.*t22.*t27.*t35.*1.2e+1-in_1_n3.*in_2_n4.*t7.*t15.*t18.*t21.*t27.*t35.*1.2e+1-in_1_n3.*in_2_n4.*t8.*t15.*t17.*t22.*t27.*t35.*1.2e+1-in_1_n3.*in_2_n4.*t8.*t15.*t18.*t21.*t27.*t35.*1.2e+1+in_1_n3.*in_4_n4.*t3.*t15.*t17.*t18.*t22.*t29.*6.0+in_2_n4.*in_3_n3.*t3.*t15.*t17.*t18.*t22.*t29.*6.0+in_1_n3.*in_2_n4.*t3.*t15.*t21.*t26.*t27.*t35.*6.0+in_1_n3.*in_2_n4.*t3.*t15.*t23.*t25.*t27.*t35.*1.2e+1-in_1_n3.*in_4_n4.*t3.*t15.*t17.*t22.*t27.*t35.*1.2e+1-in_1_n3.*in_4_n4.*t3.*t15.*t18.*t21.*t27.*t35.*1.2e+1-in_2_n4.*in_3_n3.*t3.*t15.*t17.*t22.*t27.*t35.*1.2e+1-in_2_n4.*in_3_n3.*t3.*t15.*t18.*t21.*t27.*t35.*1.2e+1+in_1_n3.*in_2_n4.*in_3_n1.*in_4_n5.*t3.*t15.*t17.*t22.*t29.*6.0+in_1_n3.*in_2_n4.*in_3_n1.*in_4_n5.*t3.*t15.*t18.*t21.*t29.*6.0;
et5 = in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t3.*t15.*t17.*t23.*t29.*1.2e+1+in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t3.*t15.*t18.*t22.*t29.*6.0-in_1_n3.*in_2_n4.*in_3_n1.*in_4_n5.*t3.*t15.*t21.*t27.*t35.*1.2e+1-in_1_n3.*in_2_n4.*in_3_n2.*in_4_n3.*t3.*t15.*t22.*t27.*t35.*1.2e+1+in_1_n3.*in_2_n4.*t3.*t15.*t17.*t18.*t22.*t27.*t35.*1.2e+1;
out_1 = et1+et2+et3+et4+et5;
end

