function varargout=sym_ststeq(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=0;
   return
  case 'npar'
   varargout{1}=12;
   return
  case 'nf'
   varargout{1}=1;
   return
  case 'nx'
   varargout{1}=1;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=1;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_ststeq_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function out_1 = sym_ststeq_rhs_1_0(in_1_n1,in2,in_3_n1,in4)
%SYM_STSTEQ_RHS_1_0
%    OUT_1 = SYM_STSTEQ_RHS_1_0(IN_1_N1,IN2,IN_3_N1,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:40

in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_2_n11 = in2(:,11);
t2 = in_1_n1.*in_2_n5;
t3 = in_2_n4+in_2_n8;
t6 = in_2_n1.^2;
t7 = in_2_n3.^2;
t12 = -in_2_n2;
t13 = 1.0./in_2_n4;
t14 = 1.0./in_2_n8;
t9 = in_2_n1.*t2;
t10 = in_2_n2.*t2;
t11 = in_2_n3.*t2;
t15 = t2+1.0;
t16 = in_2_n4+t3;
t17 = 1.0./t3;
t20 = t2.*t6.*2.0;
t24 = t2.^2.*t6;
t25 = t2.^2.*t7;
t18 = -t10;
t19 = -t11;
t21 = 1.0./t15.^3;
t22 = 1.0./t16;
t23 = in_2_n1+t9+t11;
t28 = -t25;
t26 = in_2_n1+t9+t19;
t27 = t23.^2;
t31 = t12+t18+t23;
t32 = t6+t20+t24+t28;
t29 = t26.^2;
t30 = 1.0./t26;
t33 = t30.*t31;
t34 = -t33;
out_1 = in_2_n7.*t2.*t21.*(t14.*t27.*t34.^(in_2_n8.*t13)+t17.*t32.*t34.^(t3.*t13).*2.0+t22.*t29.*t34.^(t13.*t16))-in_2_n7.*t2.*t21.*(t14.*t27.*exp(-in_2_n8.*in_2_n11)+t17.*t32.*exp(-in_2_n11.*t3).*2.0+t22.*t29.*exp(-in_2_n11.*t16));
end


function out_1 = sym_ststeq_rhs_1_1(in_1_n1,in2,in_3_n1,in4)
%SYM_STSTEQ_RHS_1_1
%    OUT_1 = SYM_STSTEQ_RHS_1_1(IN_1_N1,IN2,IN_3_N1,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:00:41

in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
in_2_n11 = in2(:,11);
in_4_n11 = in4(:,11);
t2 = in_1_n1.*in_2_n5;
t3 = in_1_n1.*in_4_n5;
t4 = in_2_n5.*in_3_n1;
t5 = in_2_n8.*in_2_n11;
t6 = in_2_n4+in_2_n8;
t7 = in_4_n4+in_4_n8;
t11 = in_2_n1.^2;
t12 = in_2_n3.^2;
t14 = in_2_n1.*in_4_n1.*2.0;
t27 = -in_2_n2;
t28 = -in_4_n2;
t29 = 1.0./in_2_n4;
t31 = 1.0./in_2_n8;
t15 = in_2_n1.*t2;
t16 = in_2_n2.*t2;
t17 = in_2_n3.*t2;
t18 = in_2_n1.*t3;
t19 = in_4_n1.*t2;
t20 = in_2_n1.*t4;
t21 = in_2_n2.*t3;
t22 = in_4_n2.*t2;
t23 = in_2_n2.*t4;
t24 = in_2_n3.*t3;
t25 = in_4_n3.*t2;
t26 = in_2_n3.*t4;
t30 = t29.^2;
t32 = t31.^2;
t33 = -t5;
t34 = t2+1.0;
t35 = in_2_n4+t6;
t36 = in_4_n4+t7;
t37 = in_2_n11.*t6;
t39 = in_2_n8.*t29;
t40 = 1.0./t6;
t52 = t3+t4;
t54 = t2.*t11.*2.0;
t55 = t3.*t11.*2.0;
t56 = t4.*t11.*2.0;
t57 = t6.*t29;
t66 = t2.^2.*t11;
t67 = t2.^2.*t12;
t70 = t2.*t4.*t12.*2.0;
t71 = t2.^2.*t14;
t74 = t2.*t3.*t12.*2.0;
t38 = in_4_n1.*t15.*4.0;
t41 = t40.^2;
t42 = exp(t33);
t43 = -t16;
t44 = -t17;
t45 = -t21;
t46 = -t22;
t47 = -t23;
t48 = -t24;
t49 = -t25;
t50 = -t26;
t51 = in_2_n11.*t35;
t53 = -t37;
t59 = 1.0./t34.^3;
t60 = 1.0./t34.^4;
t61 = 1.0./t35;
t64 = in_2_n1+t15+t17;
t65 = t29.*t35;
t69 = t4.*t54;
t72 = t17.*t25.*2.0;
t73 = t3.*t54;
t75 = -t70;
t77 = -t74;
t80 = -t67;
t86 = in_4_n1+t18+t19+t20+t24+t25+t26;
t58 = exp(t53);
t62 = t61.^2;
t63 = -t51;
t76 = -t72;
t78 = in_2_n1+t15+t44;
t79 = t64.^2;
t84 = t27+t43+t64;
t87 = in_4_n1+t18+t19+t20+t48+t49+t50;
t89 = t11+t54+t66+t80;
t95 = t28+t45+t46+t47+t86;
t68 = exp(t63);
t81 = t78.^2;
t82 = 1.0./t78;
t85 = t31.*t42.*t79;
t97 = t40.*t58.*t89.*2.0;
t103 = t14+t38+t55+t56+t69+t71+t73+t75+t76+t77;
t83 = 1.0./t81;
t88 = t61.*t68.*t81;
t90 = t82.*t84;
t99 = t82.*t95;
t91 = -t90;
t100 = t83.*t84.*t87;
t105 = t85+t88+t97;
t92 = log(t91);
t93 = t91.^t39;
t94 = t91.^t57;
t96 = t91.^t65;
t101 = -t100;
t98 = t31.*t79.*t93;
t102 = t61.*t81.*t96;
t104 = t40.*t89.*t94.*2.0;
t106 = t99+t101;
t107 = t98+t102+t104;
et1 = -in_2_n7.*t3.*t59.*t105-in_2_n7.*t4.*t59.*t105+in_2_n7.*t3.*t59.*t107+in_2_n7.*t4.*t59.*t107-in_4_n7.*t2.*t59.*t105+in_4_n7.*t2.*t59.*t107+in_2_n7.*t2.*t59.*(t31.*t79.*(t92.*t93.*(in_4_n8.*t29-in_2_n8.*in_4_n4.*t30)-t39.*t91.^(t39-1.0).*t106)+t40.*t89.*(t92.*t94.*(t7.*t29-in_4_n4.*t6.*t30)-t57.*t91.^(t57-1.0).*t106).*2.0+t61.*t81.*(t92.*t96.*(t29.*t36-in_4_n4.*t30.*t35)-t65.*t91.^(t65-1.0).*t106)+t40.*t94.*t103.*2.0-in_4_n8.*t32.*t79.*t93-t7.*t41.*t89.*t94.*2.0+t31.*t64.*t86.*t93.*2.0-t36.*t62.*t81.*t96+t61.*t78.*t87.*t96.*2.0);
et2 = in_2_n7.*t2.*t59.*(t85.*(in_4_n8.*in_2_n11+in_2_n8.*in_4_n11)+t97.*(in_2_n11.*t7+in_4_n11.*t6)+t88.*(in_2_n11.*t36+in_4_n11.*t35)-t40.*t58.*t103.*2.0+in_4_n8.*t32.*t42.*t79+t7.*t41.*t58.*t89.*2.0-t31.*t42.*t64.*t86.*2.0+t36.*t62.*t68.*t81-t61.*t68.*t78.*t87.*2.0)+in_2_n7.*t2.*t52.*t60.*t105.*3.0-in_2_n7.*t2.*t52.*t60.*t107.*3.0;
out_1 = et1+et2;
end

