function J = dslope(data, xbp, T0, T, p, v)
mps=data.coll_seg.maps;
x_shp= mps.xbp_shp; % shape of solution vector
nx=x_shp(1);
tbp  = data.coll_seg.mesh.tbp; % base points of mesh
xvals=reshape(xbp,x_shp);
Jx=coll_mesh_mat(tbp,v/T,'kron',nx); % obtain interpolation value
Jtx=coll_mesh_mat(tbp,v/T,'diff',1,'kron',nx);
Jt=xvals*coll_mesh_mat(tbp,v/T,'diff',1).';
Jtt=xvals*coll_mesh_mat(tbp,v/T,'diff',2).';
idxvec=zeros(1,nx);
idxvec(data.idx)=1;
[nx,nT0,nT,np,nv]=deal(numel(xbp),numel(T0),numel(T),numel(p),numel(v));
nu=nx+nT0+nT+np+nv;
x_idx=1:nx;
[T0_idx,T_idx]=deal(x_idx(end)+1,x_idx(end)+2); %#ok<ASGLU>
p_idx=T_idx+(1:np);
v_idx=p_idx(end)+(1:nv);
J=zeros(3,nu);
J(1,v_idx)=1;
J(2,x_idx)=idxvec*Jx;
J(2,T_idx)=-idxvec*Jt*v/T^2;
J(2,v_idx)=idxvec*Jt/T;
J(3,x_idx)=idxvec*Jtx;
J(3,T_idx)=-idxvec*Jtt*v/T^2;
J(3,v_idx)=idxvec*Jtt/T;
end
