function varargout=sys_bykov(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:10);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',7);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=3;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('sys_bykov_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = sys_bykov_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%SYS_BYKOV_RHS_0
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Dec-2025 10:21:15

t2 = in1.*in2.*in6;
t4 = in1+in2+in3-1.0;
t3 = -t2;
out1 = t3-in1.^2.*in8.*2.0+in4.*t4.^2.*2.0;
if nargout > 1
    out2 = t3-in2.*in9-in5.*t4;
end
if nargout > 2
    out3 = -in7.*t4-in3.*in7.*in10;
end
end


function [out1,out2,out3] = sys_bykov_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%SYS_BYKOV_RHS_1
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Dec-2025 10:21:15

t2 = in1.*in2.*in16;
t3 = in1.*in6.*in12;
t4 = in2.*in6.*in11;
t5 = in11+in12+in13;
t9 = in1+in2+in3-1.0;
t6 = -t2;
t7 = -t3;
t8 = -t4;
out1 = t6+t7+t8-in1.^2.*in18.*2.0+in14.*t9.^2.*2.0-in1.*in8.*in11.*4.0+in4.*t5.*t9.*4.0;
if nargout > 1
    out2 = t6+t7+t8-in2.*in19-in9.*in12-in5.*t5-in15.*t9;
end
if nargout > 2
    out3 = -in7.*t5-in17.*t9-in3.*in7.*in20-in3.*in10.*in17-in7.*in10.*in13;
end
end


function [out1,out2,out3] = sys_bykov_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%SYS_BYKOV_RHS_2
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Dec-2025 10:21:15

t2 = in11+in12+in13;
t3 = in1.*in12.*in16.*2.0;
t4 = in2.*in11.*in16.*2.0;
t5 = in6.*in11.*in12.*2.0;
t6 = -t3;
t7 = -t4;
t8 = -t5;
out1 = t6+t7+t8-in8.*in11.^2.*4.0+in4.*t2.^2.*4.0-in1.*in11.*in18.*8.0+in14.*t2.*(in1+in2+in3-1.0).*8.0;
if nargout > 1
    out2 = t6+t7+t8-in12.*in19.*2.0-in15.*t2.*2.0;
end
if nargout > 2
    out3 = in17.*t2.*-2.0-in3.*in17.*in20.*2.0-in7.*in13.*in20.*2.0-in10.*in13.*in17.*2.0;
end
end


function [out1,out2,out3] = sys_bykov_rhs_3(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20)
%SYS_BYKOV_RHS_3
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_3(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-Dec-2025 10:21:15

t2 = in11.*in12.*in16.*6.0;
t3 = -t2;
out1 = t3-in11.^2.*in18.*1.2e+1+in14.*(in11+in12+in13).^2.*1.2e+1;
if nargout > 1
    out2 = t3;
end
if nargout > 2
    out3 = in13.*in17.*in20.*-6.0;
end
end

