function varargout=sym_nmfm_demo(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=2;
   return
  case 'npar'
   varargout{1}=6;
   return
  case 'nf'
   varargout{1}=2;
   return
  case 'nx'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1  1  2  2  2  1  3  2  3];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_nmfm_demo_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2] = sym_nmfm_demo_rhs_1_0(in1,in2,in3,in4)
%SYM_NMFM_DEMO_RHS_1_0
%    [OUT_1,OUT_2] = SYM_NMFM_DEMO_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:04:34

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
t2 = cosh(1.0);
t3 = tanh(1.0);
t4 = t2.^2;
out_1 = -in_1_n1-in_2_n1.*t4.*(t3+tanh(in_1_n3.*in_2_n2-1.0))+in_2_n3.*t4.*(t3+tanh(in_1_n6.*in_2_n4-1.0));
if nargout > 1
    out_2 = -in_1_n2-in_2_n1.*t4.*(t3+tanh(in_1_n4.*in_2_n2-1.0))+in_2_n3.*t4.*(t3+tanh(in_1_n5.*in_2_n4-1.0));
end
end


function [out_1,out_2] = sym_nmfm_demo_rhs_1_1(in1,in2,in3,in4)
%SYM_NMFM_DEMO_RHS_1_1
%    [OUT_1,OUT_2] = SYM_NMFM_DEMO_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:04:34

in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
t2 = cosh(1.0);
t3 = tanh(1.0);
t4 = in_1_n3.*in_2_n2;
t5 = in_1_n4.*in_2_n2;
t6 = in_1_n5.*in_2_n4;
t7 = in_1_n6.*in_2_n4;
t8 = t2.^2;
t9 = t4-1.0;
t10 = t5-1.0;
t11 = t6-1.0;
t12 = t7-1.0;
t13 = tanh(t9);
t14 = tanh(t10);
t15 = tanh(t11);
t16 = tanh(t12);
out_1 = -in_3_n1-in_4_n1.*t8.*(t3+t13)+in_4_n3.*t8.*(t3+t16)+in_2_n1.*t8.*(t13.^2-1.0).*(in_1_n3.*in_4_n2+in_2_n2.*in_3_n3)-in_2_n3.*t8.*(t16.^2-1.0).*(in_1_n6.*in_4_n4+in_2_n4.*in_3_n6);
if nargout > 1
    out_2 = -in_3_n2-in_4_n1.*t8.*(t3+t14)+in_4_n3.*t8.*(t3+t15)+in_2_n1.*t8.*(t14.^2-1.0).*(in_1_n4.*in_4_n2+in_2_n2.*in_3_n4)-in_2_n3.*t8.*(t15.^2-1.0).*(in_1_n5.*in_4_n4+in_2_n4.*in_3_n5);
end
end


function [out_1,out_2] = sym_nmfm_demo_rhs_1_2(in1,in2,in3,in4)
%SYM_NMFM_DEMO_RHS_1_2
%    [OUT_1,OUT_2] = SYM_NMFM_DEMO_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:04:34

in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
t2 = cosh(1.0);
t3 = in_1_n3.*in_2_n2;
t4 = in_1_n4.*in_2_n2;
t5 = in_1_n5.*in_2_n4;
t6 = in_1_n6.*in_2_n4;
t7 = in_1_n3.*in_4_n2;
t8 = in_2_n2.*in_3_n3;
t9 = in_1_n4.*in_4_n2;
t10 = in_2_n2.*in_3_n4;
t11 = in_1_n5.*in_4_n4;
t12 = in_2_n4.*in_3_n5;
t13 = in_1_n6.*in_4_n4;
t14 = in_2_n4.*in_3_n6;
t15 = t2.^2;
t16 = t3-1.0;
t17 = t4-1.0;
t18 = t5-1.0;
t19 = t6-1.0;
t24 = t7+t8;
t25 = t9+t10;
t26 = t11+t12;
t27 = t13+t14;
t20 = tanh(t16);
t21 = tanh(t17);
t22 = tanh(t18);
t23 = tanh(t19);
t28 = t20.^2;
t29 = t21.^2;
t30 = t22.^2;
t31 = t23.^2;
t32 = t28-1.0;
t33 = t29-1.0;
t34 = t30-1.0;
t35 = t31-1.0;
out_1 = in_4_n1.*t15.*t24.*t32.*2.0-in_4_n3.*t15.*t27.*t35.*2.0+in_2_n1.*in_3_n3.*in_4_n2.*t15.*t32.*2.0-in_2_n3.*in_3_n6.*in_4_n4.*t15.*t35.*2.0-in_2_n1.*t15.*t20.*t24.^2.*t32.*2.0+in_2_n3.*t15.*t23.*t27.^2.*t35.*2.0;
if nargout > 1
    out_2 = in_4_n1.*t15.*t25.*t33.*2.0-in_4_n3.*t15.*t26.*t34.*2.0+in_2_n1.*in_3_n4.*in_4_n2.*t15.*t33.*2.0-in_2_n3.*in_3_n5.*in_4_n4.*t15.*t34.*2.0-in_2_n1.*t15.*t21.*t25.^2.*t33.*2.0+in_2_n3.*t15.*t22.*t26.^2.*t34.*2.0;
end
end


function [out_1,out_2] = sym_nmfm_demo_rhs_1_3(in1,in2,in3,in4)
%SYM_NMFM_DEMO_RHS_1_3
%    [OUT_1,OUT_2] = SYM_NMFM_DEMO_RHS_1_3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:04:34

in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
t2 = cosh(1.0);
t3 = in_1_n3.*in_2_n2;
t4 = in_1_n4.*in_2_n2;
t5 = in_1_n5.*in_2_n4;
t6 = in_1_n6.*in_2_n4;
t7 = in_1_n3.*in_4_n2;
t8 = in_2_n2.*in_3_n3;
t9 = in_1_n4.*in_4_n2;
t10 = in_2_n2.*in_3_n4;
t11 = in_1_n5.*in_4_n4;
t12 = in_2_n4.*in_3_n5;
t13 = in_1_n6.*in_4_n4;
t14 = in_2_n4.*in_3_n6;
t15 = t2.^2;
t16 = t3-1.0;
t17 = t4-1.0;
t18 = t5-1.0;
t19 = t6-1.0;
t24 = t7+t8;
t25 = t9+t10;
t26 = t11+t12;
t27 = t13+t14;
t20 = tanh(t16);
t21 = tanh(t17);
t22 = tanh(t18);
t23 = tanh(t19);
t28 = t24.^3;
t29 = t25.^3;
t30 = t26.^3;
t31 = t27.^3;
t32 = t20.^2;
t33 = t21.^2;
t34 = t22.^2;
t35 = t23.^2;
t36 = t32-1.0;
t37 = t33-1.0;
t38 = t34-1.0;
t39 = t35-1.0;
out_1 = in_2_n1.*t15.*t28.*t36.^2.*2.0-in_2_n3.*t15.*t31.*t39.^2.*2.0+in_3_n3.*in_4_n1.*in_4_n2.*t15.*t36.*6.0-in_3_n6.*in_4_n3.*in_4_n4.*t15.*t39.*6.0+in_2_n1.*t15.*t28.*t32.*t36.*4.0-in_2_n3.*t15.*t31.*t35.*t39.*4.0-in_4_n1.*t15.*t20.*t24.^2.*t36.*6.0+in_4_n3.*t15.*t23.*t27.^2.*t39.*6.0-in_2_n1.*in_3_n3.*in_4_n2.*t15.*t20.*t24.*t36.*1.2e+1+in_2_n3.*in_3_n6.*in_4_n4.*t15.*t23.*t27.*t39.*1.2e+1;
if nargout > 1
    out_2 = in_2_n1.*t15.*t29.*t37.^2.*2.0-in_2_n3.*t15.*t30.*t38.^2.*2.0+in_3_n4.*in_4_n1.*in_4_n2.*t15.*t37.*6.0-in_3_n5.*in_4_n3.*in_4_n4.*t15.*t38.*6.0+in_2_n1.*t15.*t29.*t33.*t37.*4.0-in_2_n3.*t15.*t30.*t34.*t38.*4.0-in_4_n1.*t15.*t21.*t25.^2.*t37.*6.0+in_4_n3.*t15.*t22.*t26.^2.*t38.*6.0-in_2_n1.*in_3_n4.*in_4_n2.*t15.*t21.*t25.*t37.*1.2e+1+in_2_n3.*in_3_n5.*in_4_n4.*t15.*t22.*t26.*t38.*1.2e+1;
end
end


function [out_1,out_2] = sym_nmfm_demo_rhs_1_4(in1,in2,in3,in4)
%SYM_NMFM_DEMO_RHS_1_4
%    [OUT_1,OUT_2] = SYM_NMFM_DEMO_RHS_1_4(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:04:34

in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
t2 = cosh(1.0);
t3 = in_1_n3.*in_2_n2;
t4 = in_1_n4.*in_2_n2;
t5 = in_1_n5.*in_2_n4;
t6 = in_1_n6.*in_2_n4;
t7 = in_1_n3.*in_4_n2;
t8 = in_2_n2.*in_3_n3;
t9 = in_1_n4.*in_4_n2;
t10 = in_2_n2.*in_3_n4;
t11 = in_1_n5.*in_4_n4;
t12 = in_2_n4.*in_3_n5;
t13 = in_1_n6.*in_4_n4;
t14 = in_2_n4.*in_3_n6;
t15 = in_4_n2.^2;
t16 = in_4_n4.^2;
t17 = t2.^2;
t18 = t3-1.0;
t19 = t4-1.0;
t20 = t5-1.0;
t21 = t6-1.0;
t26 = t7+t8;
t27 = t9+t10;
t28 = t11+t12;
t29 = t13+t14;
t22 = tanh(t18);
t23 = tanh(t19);
t24 = tanh(t20);
t25 = tanh(t21);
t30 = t26.^2;
t31 = t26.^3;
t33 = t27.^2;
t34 = t27.^3;
t36 = t28.^2;
t37 = t28.^3;
t39 = t29.^2;
t40 = t29.^3;
t32 = t30.^2;
t35 = t33.^2;
t38 = t36.^2;
t41 = t39.^2;
t42 = t22.^2;
t43 = t23.^2;
t44 = t24.^2;
t45 = t25.^2;
t46 = t42-1.0;
t47 = t43-1.0;
t48 = t44-1.0;
t49 = t45-1.0;
t50 = t46.^2;
t51 = t47.^2;
t52 = t48.^2;
t53 = t49.^2;
out_1 = in_4_n1.*t17.*t31.*t50.*8.0-in_4_n3.*t17.*t40.*t53.*8.0-in_2_n1.*t17.*t22.*t32.*t50.*1.6e+1+in_2_n3.*t17.*t25.*t41.*t53.*1.6e+1+in_4_n1.*t17.*t31.*t42.*t46.*1.6e+1-in_4_n3.*t17.*t40.*t45.*t49.*1.6e+1-in_2_n1.*t17.*t22.^3.*t32.*t46.*8.0+in_2_n3.*t17.*t25.^3.*t41.*t49.*8.0-in_2_n1.*in_3_n3.^2.*t15.*t17.*t22.*t46.*2.4e+1+in_2_n3.*in_3_n6.^2.*t16.*t17.*t25.*t49.*2.4e+1+in_2_n1.*in_3_n3.*in_4_n2.*t17.*t30.*t50.*2.4e+1-in_2_n3.*in_3_n6.*in_4_n4.*t17.*t39.*t53.*2.4e+1-in_3_n3.*in_4_n1.*in_4_n2.*t17.*t22.*t26.*t46.*4.8e+1+in_2_n1.*in_3_n3.*in_4_n2.*t17.*t30.*t42.*t46.*4.8e+1+in_3_n6.*in_4_n3.*in_4_n4.*t17.*t25.*t29.*t49.*4.8e+1-in_2_n3.*in_3_n6.*in_4_n4.*t17.*t39.*t45.*t49.*4.8e+1;
if nargout > 1
    out_2 = in_4_n1.*t17.*t34.*t51.*8.0-in_4_n3.*t17.*t37.*t52.*8.0-in_2_n1.*t17.*t23.*t35.*t51.*1.6e+1+in_2_n3.*t17.*t24.*t38.*t52.*1.6e+1+in_4_n1.*t17.*t34.*t43.*t47.*1.6e+1-in_4_n3.*t17.*t37.*t44.*t48.*1.6e+1-in_2_n1.*t17.*t23.^3.*t35.*t47.*8.0+in_2_n3.*t17.*t24.^3.*t38.*t48.*8.0-in_2_n1.*in_3_n4.^2.*t15.*t17.*t23.*t47.*2.4e+1+in_2_n3.*in_3_n5.^2.*t16.*t17.*t24.*t48.*2.4e+1+in_2_n1.*in_3_n4.*in_4_n2.*t17.*t33.*t51.*2.4e+1-in_2_n3.*in_3_n5.*in_4_n4.*t17.*t36.*t52.*2.4e+1-in_3_n4.*in_4_n1.*in_4_n2.*t17.*t23.*t27.*t47.*4.8e+1+in_2_n1.*in_3_n4.*in_4_n2.*t17.*t33.*t43.*t47.*4.8e+1+in_3_n5.*in_4_n3.*in_4_n4.*t17.*t24.*t28.*t48.*4.8e+1-in_2_n3.*in_3_n5.*in_4_n4.*t17.*t36.*t44.*t48.*4.8e+1;
end
end


function [out_1,out_2] = sym_nmfm_demo_rhs_1_5(in1,in2,in3,in4)
%SYM_NMFM_DEMO_RHS_1_5
%    [OUT_1,OUT_2] = SYM_NMFM_DEMO_RHS_1_5(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Feb-2025 00:04:34

in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
t2 = cosh(1.0);
t3 = in_1_n3.*in_2_n2;
t4 = in_1_n4.*in_2_n2;
t5 = in_1_n5.*in_2_n4;
t6 = in_1_n6.*in_2_n4;
t7 = in_1_n3.*in_4_n2;
t8 = in_2_n2.*in_3_n3;
t9 = in_1_n4.*in_4_n2;
t10 = in_2_n2.*in_3_n4;
t11 = in_1_n5.*in_4_n4;
t12 = in_2_n4.*in_3_n5;
t13 = in_1_n6.*in_4_n4;
t14 = in_2_n4.*in_3_n6;
t15 = in_3_n3.^2;
t16 = in_3_n4.^2;
t17 = in_3_n5.^2;
t18 = in_3_n6.^2;
t19 = in_4_n2.^2;
t20 = in_4_n4.^2;
t21 = t2.^2;
t22 = t3-1.0;
t23 = t4-1.0;
t24 = t5-1.0;
t25 = t6-1.0;
t30 = t7+t8;
t31 = t9+t10;
t32 = t11+t12;
t33 = t13+t14;
t26 = tanh(t22);
t27 = tanh(t23);
t28 = tanh(t24);
t29 = tanh(t25);
t34 = t30.^2;
t35 = t30.^3;
t37 = t31.^2;
t38 = t30.^5;
t39 = t31.^3;
t41 = t31.^5;
t42 = t32.^2;
t43 = t32.^3;
t45 = t33.^2;
t46 = t32.^5;
t47 = t33.^3;
t49 = t33.^5;
t36 = t34.^2;
t40 = t37.^2;
t44 = t42.^2;
t48 = t45.^2;
t50 = t26.^2;
t51 = t26.^3;
t52 = t27.^2;
t53 = t27.^3;
t54 = t28.^2;
t55 = t28.^3;
t56 = t29.^2;
t57 = t29.^3;
t58 = t50-1.0;
t59 = t52-1.0;
t60 = t54-1.0;
t61 = t56-1.0;
t62 = t58.^2;
t63 = t59.^2;
t64 = t60.^2;
t65 = t61.^2;
et1 = in_2_n1.*t21.*t38.*t58.^3.*1.6e+1-in_2_n3.*t21.*t49.*t61.^3.*1.6e+1-in_4_n1.*t21.*t26.*t36.*t62.*8.0e+1+in_2_n1.*t21.*t38.*t50.*t62.*8.8e+1+in_4_n3.*t21.*t29.*t48.*t65.*8.0e+1-in_4_n1.*t21.*t36.*t51.*t58.*4.0e+1-in_2_n3.*t21.*t49.*t56.*t65.*8.8e+1+in_4_n3.*t21.*t48.*t57.*t61.*4.0e+1+in_2_n1.*t21.*t38.*t50.^2.*t58.*1.6e+1-in_2_n3.*t21.*t49.*t56.^2.*t61.*1.6e+1+in_2_n1.*t15.*t19.*t21.*t30.*t62.*1.2e+2-in_2_n3.*t18.*t20.*t21.*t33.*t65.*1.2e+2-in_4_n1.*t15.*t19.*t21.*t26.*t58.*1.2e+2+in_4_n3.*t18.*t20.*t21.*t29.*t61.*1.2e+2+in_3_n3.*in_4_n1.*in_4_n2.*t21.*t34.*t62.*1.2e+2-in_3_n6.*in_4_n3.*in_4_n4.*t21.*t45.*t65.*1.2e+2-in_2_n1.*in_3_n3.*in_4_n2.*t21.*t26.*t35.*t62.*3.2e+2-in_2_n1.*in_3_n3.*in_4_n2.*t21.*t35.*t51.*t58.*1.6e+2+in_2_n3.*in_3_n6.*in_4_n4.*t21.*t29.*t47.*t65.*3.2e+2;
et2 = in_3_n3.*in_4_n1.*in_4_n2.*t21.*t34.*t50.*t58.*2.4e+2+in_2_n3.*in_3_n6.*in_4_n4.*t21.*t47.*t57.*t61.*1.6e+2-in_3_n6.*in_4_n3.*in_4_n4.*t21.*t45.*t56.*t61.*2.4e+2+in_2_n1.*t15.*t19.*t21.*t30.*t50.*t58.*2.4e+2-in_2_n3.*t18.*t20.*t21.*t33.*t56.*t61.*2.4e+2;
out_1 = et1+et2;
if nargout > 1
    et3 = in_2_n1.*t21.*t41.*t59.^3.*1.6e+1-in_2_n3.*t21.*t46.*t60.^3.*1.6e+1-in_4_n1.*t21.*t27.*t40.*t63.*8.0e+1+in_2_n1.*t21.*t41.*t52.*t63.*8.8e+1+in_4_n3.*t21.*t28.*t44.*t64.*8.0e+1-in_2_n3.*t21.*t46.*t54.*t64.*8.8e+1-in_4_n1.*t21.*t40.*t53.*t59.*4.0e+1+in_4_n3.*t21.*t44.*t55.*t60.*4.0e+1+in_2_n1.*t21.*t41.*t52.^2.*t59.*1.6e+1-in_2_n3.*t21.*t46.*t54.^2.*t60.*1.6e+1+in_2_n1.*t16.*t19.*t21.*t31.*t63.*1.2e+2-in_2_n3.*t17.*t20.*t21.*t32.*t64.*1.2e+2-in_4_n1.*t16.*t19.*t21.*t27.*t59.*1.2e+2+in_4_n3.*t17.*t20.*t21.*t28.*t60.*1.2e+2+in_3_n4.*in_4_n1.*in_4_n2.*t21.*t37.*t63.*1.2e+2-in_3_n5.*in_4_n3.*in_4_n4.*t21.*t42.*t64.*1.2e+2-in_2_n1.*in_3_n4.*in_4_n2.*t21.*t27.*t39.*t63.*3.2e+2+in_2_n3.*in_3_n5.*in_4_n4.*t21.*t28.*t43.*t64.*3.2e+2-in_2_n1.*in_3_n4.*in_4_n2.*t21.*t39.*t53.*t59.*1.6e+2;
    et4 = in_2_n3.*in_3_n5.*in_4_n4.*t21.*t43.*t55.*t60.*1.6e+2+in_3_n4.*in_4_n1.*in_4_n2.*t21.*t37.*t52.*t59.*2.4e+2-in_3_n5.*in_4_n3.*in_4_n4.*t21.*t42.*t54.*t60.*2.4e+2+in_2_n1.*t16.*t19.*t21.*t31.*t52.*t59.*2.4e+2-in_2_n3.*t17.*t20.*t21.*t32.*t54.*t60.*2.4e+2;
    out_2 = et3+et4;
end
end

