function varargout=sys(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('x',1:2,'p',3:3);
   return
  case 'argsize'
   varargout{1}=struct('x',2,'p',1);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=4;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('sys_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = sys_rhs_0(in1,in2,in3,in4,in5,in6)
%SYS_RHS_0
%    [OUT1,OUT2] = SYS_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Dec-2025 11:49:04

out1 = in2;
if nargout > 1
    out2 = -in3.*exp(in1);
end
end


function [out1,out2] = sys_rhs_1(in1,in2,in3,in4,in5,in6)
%SYS_RHS_1
%    [OUT1,OUT2] = SYS_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Dec-2025 11:49:04

out1 = in5;
if nargout > 1
    t2 = exp(in1);
    out2 = -in6.*t2-in3.*in4.*t2;
end
end


function [out1,out2] = sys_rhs_2(in1,in2,in3,in4,in5,in6)
%SYS_RHS_2
%    [OUT1,OUT2] = SYS_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Dec-2025 11:49:04

out1 = 0.0;
if nargout > 1
    t2 = exp(in1);
    out2 = -in3.*in4.^2.*t2-in4.*in6.*t2.*2.0;
end
end


function [out1,out2] = sys_rhs_3(in1,in2,in3,in4,in5,in6)
%SYS_RHS_3
%    [OUT1,OUT2] = SYS_RHS_3(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Dec-2025 11:49:04

out1 = 0.0;
if nargout > 1
    t2 = exp(in1);
    out2 = -in3.*in4.^3.*t2-in4.^2.*in6.*t2.*3.0;
end
end


function [out1,out2] = sys_rhs_4(in1,in2,in3,in4,in5,in6)
%SYS_RHS_4
%    [OUT1,OUT2] = SYS_RHS_4(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Dec-2025 11:49:04

out1 = 0.0;
if nargout > 1
    t2 = exp(in1);
    out2 = -in3.*in4.^4.*t2-in4.^3.*in6.*t2.*4.0;
end
end

